# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package Iodef;
use base qw(Exporter);
use base qw(DynaLoader);
package Iodefc;
bootstrap Iodef;
package Iodef;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Iodef;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Iodef;


############# Class : Iodef::LibIodefError ##############

package Iodef::LibIodefError;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Iodef );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Iodefc::delete_LibIodefError($self);
        delete $OWNER{$self};
    }
}

sub new {
    my $pkg = shift;
    my $self = Iodefc::new_LibIodefError(@_);
    bless $self, $pkg if defined($self);
}

*getCode = *Iodefc::LibIodefError_getCode;
*what = *Iodefc::LibIodefError_what;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Iodef::IODEFV2Criterion ##############

package Iodef::IODEFV2Criterion;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Iodef );
%OWNER = ();
%ITERATORS = ();
*OPERATOR_NOT = *Iodefc::IODEFV2Criterion_OPERATOR_NOT;
*OPERATOR_NOCASE = *Iodefc::IODEFV2Criterion_OPERATOR_NOCASE;
*OPERATOR_EQUAL = *Iodefc::IODEFV2Criterion_OPERATOR_EQUAL;
*OPERATOR_EQUAL_NOCASE = *Iodefc::IODEFV2Criterion_OPERATOR_EQUAL_NOCASE;
*OPERATOR_NOT_EQUAL = *Iodefc::IODEFV2Criterion_OPERATOR_NOT_EQUAL;
*OPERATOR_NOT_EQUAL_NOCASE = *Iodefc::IODEFV2Criterion_OPERATOR_NOT_EQUAL_NOCASE;
*OPERATOR_LESSER = *Iodefc::IODEFV2Criterion_OPERATOR_LESSER;
*OPERATOR_LESSER_OR_EQUAL = *Iodefc::IODEFV2Criterion_OPERATOR_LESSER_OR_EQUAL;
*OPERATOR_GREATER = *Iodefc::IODEFV2Criterion_OPERATOR_GREATER;
*OPERATOR_GREATER_OR_EQUAL = *Iodefc::IODEFV2Criterion_OPERATOR_GREATER_OR_EQUAL;
*OPERATOR_SUBSTR = *Iodefc::IODEFV2Criterion_OPERATOR_SUBSTR;
*OPERATOR_SUBSTR_NOCASE = *Iodefc::IODEFV2Criterion_OPERATOR_SUBSTR_NOCASE;
*OPERATOR_NOT_SUBSTR = *Iodefc::IODEFV2Criterion_OPERATOR_NOT_SUBSTR;
*OPERATOR_NOT_SUBSTR_NOCASE = *Iodefc::IODEFV2Criterion_OPERATOR_NOT_SUBSTR_NOCASE;
*OPERATOR_REGEX = *Iodefc::IODEFV2Criterion_OPERATOR_REGEX;
*OPERATOR_REGEX_NOCASE = *Iodefc::IODEFV2Criterion_OPERATOR_REGEX_NOCASE;
*OPERATOR_NOT_REGEX = *Iodefc::IODEFV2Criterion_OPERATOR_NOT_REGEX;
*OPERATOR_NOT_REGEX_NOCASE = *Iodefc::IODEFV2Criterion_OPERATOR_NOT_REGEX_NOCASE;
*OPERATOR_NULL = *Iodefc::IODEFV2Criterion_OPERATOR_NULL;
*OPERATOR_NOT_NULL = *Iodefc::IODEFV2Criterion_OPERATOR_NOT_NULL;
sub new {
    my $pkg = shift;
    my $self = Iodefc::new_IODEFV2Criterion(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Iodefc::delete_IODEFV2Criterion($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Iodef::IODEFV2Criteria ##############

package Iodef::IODEFV2Criteria;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Iodef );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Iodefc::delete_IODEFV2Criteria($self);
        delete $OWNER{$self};
    }
}

sub new {
    my $pkg = shift;
    my $self = Iodefc::new_IODEFV2Criteria(@_);
    bless $self, $pkg if defined($self);
}

*match = *Iodefc::IODEFV2Criteria_match;
*clone = *Iodefc::IODEFV2Criteria_clone;
*andCriteria = *Iodefc::IODEFV2Criteria_andCriteria;
*orCriteria = *Iodefc::IODEFV2Criteria_orCriteria;
*toString = *Iodefc::IODEFV2Criteria_toString;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Iodef::IODEFV2Value ##############

package Iodef::IODEFV2Value;
use overload
    "<=" => sub { $_[0]->__le__($_[1])},
    ">=" => sub { $_[0]->__ge__($_[1])},
    "<" => sub { $_[0]->__lt__($_[1])},
    "!=" => sub { $_[0]->__ne__($_[1])},
    "==" => sub { $_[0]->__eq__($_[1])},
    ">" => sub { $_[0]->__gt__($_[1])},
    "=" => sub { my $class = ref($_[0]); $class->new($_[0]) },
    "fallback" => 1;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Iodef );
%OWNER = ();
%ITERATORS = ();
*TYPE_UNKNOWN = *Iodefc::IODEFV2Value_TYPE_UNKNOWN;
*TYPE_INT8 = *Iodefc::IODEFV2Value_TYPE_INT8;
*TYPE_UINT8 = *Iodefc::IODEFV2Value_TYPE_UINT8;
*TYPE_INT16 = *Iodefc::IODEFV2Value_TYPE_INT16;
*TYPE_UINT16 = *Iodefc::IODEFV2Value_TYPE_UINT16;
*TYPE_INT32 = *Iodefc::IODEFV2Value_TYPE_INT32;
*TYPE_UINT32 = *Iodefc::IODEFV2Value_TYPE_UINT32;
*TYPE_INT64 = *Iodefc::IODEFV2Value_TYPE_INT64;
*TYPE_UINT64 = *Iodefc::IODEFV2Value_TYPE_UINT64;
*TYPE_FLOAT = *Iodefc::IODEFV2Value_TYPE_FLOAT;
*TYPE_DOUBLE = *Iodefc::IODEFV2Value_TYPE_DOUBLE;
*TYPE_STRING = *Iodefc::IODEFV2Value_TYPE_STRING;
*TYPE_TIME = *Iodefc::IODEFV2Value_TYPE_TIME;
*TYPE_DATA = *Iodefc::IODEFV2Value_TYPE_DATA;
*TYPE_ENUM = *Iodefc::IODEFV2Value_TYPE_ENUM;
*TYPE_LIST = *Iodefc::IODEFV2Value_TYPE_LIST;
*TYPE_CLASS = *Iodefc::IODEFV2Value_TYPE_CLASS;
*getType = *Iodefc::IODEFV2Value_getType;
*isNull = *Iodefc::IODEFV2Value_isNull;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Iodefc::delete_IODEFV2Value($self);
        delete $OWNER{$self};
    }
}

sub new {
    my $pkg = shift;
    my $self = Iodefc::new_IODEFV2Value(@_);
    bless $self, $pkg if defined($self);
}

*match = *Iodefc::IODEFV2Value_match;
*clone = *Iodefc::IODEFV2Value_clone;
*toString = *Iodefc::IODEFV2Value_toString;
*__le__ = *Iodefc::IODEFV2Value___le__;
*__ge__ = *Iodefc::IODEFV2Value___ge__;
*__lt__ = *Iodefc::IODEFV2Value___lt__;
*__gt__ = *Iodefc::IODEFV2Value___gt__;
*__eq__ = *Iodefc::IODEFV2Value___eq__;
*__ne__ = *Iodefc::IODEFV2Value___ne__;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Iodef::IODEFV2Path ##############

package Iodef::IODEFV2Path;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Iodef );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Iodefc::new_IODEFV2Path(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Iodefc::delete_IODEFV2Path($self);
        delete $OWNER{$self};
    }
}

*set = *Iodefc::IODEFV2Path_set;
*getClass = *Iodefc::IODEFV2Path_getClass;
*getValueType = *Iodefc::IODEFV2Path_getValueType;
*setIndex = *Iodefc::IODEFV2Path_setIndex;
*undefineIndex = *Iodefc::IODEFV2Path_undefineIndex;
*getIndex = *Iodefc::IODEFV2Path_getIndex;
*makeChild = *Iodefc::IODEFV2Path_makeChild;
*makeParent = *Iodefc::IODEFV2Path_makeParent;
*compare = *Iodefc::IODEFV2Path_compare;
*clone = *Iodefc::IODEFV2Path_clone;
*checkOperator = *Iodefc::IODEFV2Path_checkOperator;
*getApplicableOperators = *Iodefc::IODEFV2Path_getApplicableOperators;
*getName = *Iodefc::IODEFV2Path_getName;
*isAmbiguous = *Iodefc::IODEFV2Path_isAmbiguous;
*hasLists = *Iodefc::IODEFV2Path_hasLists;
*isList = *Iodefc::IODEFV2Path_isList;
*getDepth = *Iodefc::IODEFV2Path_getDepth;
*get = *Iodefc::IODEFV2Path_get;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Iodef::IODEFV2Time ##############

package Iodef::IODEFV2Time;
use overload
    "<=" => sub { $_[0]->__le__($_[1])},
    "!=" => sub { $_[0]->__ne__($_[1])},
    ">=" => sub { $_[0]->__ge__($_[1])},
    "<" => sub { $_[0]->__lt__($_[1])},
    "==" => sub { $_[0]->__eq__($_[1])},
    ">" => sub { $_[0]->__gt__($_[1])},
    "=" => sub { my $class = ref($_[0]); $class->new($_[0]) },
    "fallback" => 1;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Iodef );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Iodefc::new_IODEFV2Time(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Iodefc::delete_IODEFV2Time($self);
        delete $OWNER{$self};
    }
}

*set = *Iodefc::IODEFV2Time_set;
*setSec = *Iodefc::IODEFV2Time_setSec;
*setUSec = *Iodefc::IODEFV2Time_setUSec;
*setGmtOffset = *Iodefc::IODEFV2Time_setGmtOffset;
*getSec = *Iodefc::IODEFV2Time_getSec;
*getUSec = *Iodefc::IODEFV2Time_getUSec;
*getGmtOffset = *Iodefc::IODEFV2Time_getGmtOffset;
*getTime = *Iodefc::IODEFV2Time_getTime;
*clone = *Iodefc::IODEFV2Time_clone;
*toString = *Iodefc::IODEFV2Time_toString;
*__ne__ = *Iodefc::IODEFV2Time___ne__;
*__ge__ = *Iodefc::IODEFV2Time___ge__;
*__le__ = *Iodefc::IODEFV2Time___le__;
*__eq__ = *Iodefc::IODEFV2Time___eq__;
*__gt__ = *Iodefc::IODEFV2Time___gt__;
*__lt__ = *Iodefc::IODEFV2Time___lt__;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Iodef::IODEFV2Class ##############

package Iodef::IODEFV2Class;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Iodef );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Iodefc::new_IODEFV2Class(@_);
    bless $self, $pkg if defined($self);
}

*getDepth = *Iodefc::IODEFV2Class_getDepth;
*get = *Iodefc::IODEFV2Class_get;
*getChildCount = *Iodefc::IODEFV2Class_getChildCount;
*isList = *Iodefc::IODEFV2Class_isList;
*isKeyedList = *Iodefc::IODEFV2Class_isKeyedList;
*getName = *Iodefc::IODEFV2Class_getName;
*toString = *Iodefc::IODEFV2Class_toString;
*getValueType = *Iodefc::IODEFV2Class_getValueType;
*getPath = *Iodefc::IODEFV2Class_getPath;
*getEnumValues = *Iodefc::IODEFV2Class_getEnumValues;
*getApplicableOperator = *Iodefc::IODEFV2Class_getApplicableOperator;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Iodefc::delete_IODEFV2Class($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Iodef::IODEFV2 ##############

package Iodef::IODEFV2;
use overload
    "==" => sub { $_[0]->__eq__($_[1])},
    "=" => sub { my $class = ref($_[0]); $class->new($_[0]) },
    "fallback" => 1;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Iodef );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Iodefc::delete_IODEFV2($self);
        delete $OWNER{$self};
    }
}

sub new {
    my $pkg = shift;
    my $self = Iodefc::new_IODEFV2(@_);
    bless $self, $pkg if defined($self);
}

*set = *Iodefc::IODEFV2_set;
*clone = *Iodefc::IODEFV2_clone;
*getId = *Iodefc::IODEFV2_getId;
*toString = *Iodefc::IODEFV2_toString;
*toJSON = *Iodefc::IODEFV2_toJSON;
*toBinary = *Iodefc::IODEFV2_toBinary;
*__eq__ = *Iodefc::IODEFV2___eq__;
*get = *Iodefc::IODEFV2_get;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package Iodef;

1;
