
/*****
*
* Copyright (C) 2004-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@prelude-ids.com>
*
* This file is part of the Libiodefv2 library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/*
 * This file was automatically generated by our generator, version 1
 *
 * Do not make changes to this file unless you know what you are doing.
 * modify the template interface file instead.
 * IODEFV2 version : RFC5070-bis-26
 * Template file: generate-additional-data.c.mako
 *
 */


#include "libmissing.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <netinet/in.h>

#include "libiodefv2-log.h"
#include "libiodefv2-string.h"
#include "libiodefv2-error.h"
#include "libiodefv2-inttypes.h"
#include "iodefv2.h"
#include "iodefv2-tree-wrap.h"
#include "iodefv2-additional-data.h"
#include "iodefv2-document-id.h"

#define IODEFV2_ADDITIONAL_DATA_ACCESSOR(name, type)                                                             \
int iodefv2_additional_data_new_ ## name ## _ref_fast(iodefv2_additional_data_t **ad, const char *data, size_t len)\
{                                                                                                              \
        return iodefv2_additional_data_new_ptr_ref_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_ ## type, data, len + 1);        \
}                                                                                                                                                        \
                                                                                                                                                         \
int iodefv2_additional_data_new_ ## name ## _ref(iodefv2_additional_data_t **ad, const char *data)                 \
{                                                                                                                                                        \
        return iodefv2_additional_data_new_ ## name ## _ref_fast(ad, data, strlen(data));                              \
}                                                                                                                                                        \
                                                                                                                                                         \
int iodefv2_additional_data_set_ ## name ## _ref_fast(iodefv2_additional_data_t *ad, const char *data, size_t len) \
{                                                                                                                                                        \
        return iodefv2_additional_data_set_ptr_ref_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_ ## type, data, len + 1);        \
}                                                                                                                                                        \
                                                                                                                                                         \
int iodefv2_additional_data_set_ ## name ## _ref(iodefv2_additional_data_t *ad, const char *data)                  \
{                                                                                                                                                        \
        return iodefv2_additional_data_set_ ## name ## _ref_fast(ad, data, strlen(data));                              \
}                                                                                                                                                        \
                                                                                                                                                         \
int iodefv2_additional_data_new_ ## name ## _dup_fast(iodefv2_additional_data_t **ad, const char *data, size_t len)\
{                                                                                                                                                        \
        return iodefv2_additional_data_new_ptr_dup_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_ ## type, data, len + 1);        \
}                                                                                                                                                       \
                                                                                                               \
int iodefv2_additional_data_new_ ## name ## _dup(iodefv2_additional_data_t **ad, const char *data)                 \
{                                                                                                              \
        return iodefv2_additional_data_new_ ## name ## _dup_fast(ad, data, strlen(data));                        \
}                                                                                                              \
                                                                                                               \
int iodefv2_additional_data_set_ ## name ## _dup_fast(iodefv2_additional_data_t *ad, const char *data, size_t len) \
{                                                                                                              \
        return iodefv2_additional_data_set_ptr_dup_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_ ## type, data, len + 1); \
}                                                                                                              \
                                                                                                               \
int iodefv2_additional_data_set_ ## name ## _dup(iodefv2_additional_data_t *ad, const char *data)                  \
{                                                                                                                                                   \
        return iodefv2_additional_data_set_ ## name ## _dup_fast(ad, data, strlen(data));                        \
}                                                                                                              \
                                                                                                               \
int iodefv2_additional_data_new_ ## name ## _nodup_fast(iodefv2_additional_data_t **ad, char *data, size_t len)    \
{                                                                                                                   \
        return iodefv2_additional_data_new_ptr_nodup_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_ ## type, data, len + 1);\
}                                                                                                              \
                                                                                                               \
int iodefv2_additional_data_new_ ## name ## _nodup(iodefv2_additional_data_t **ad, char *data)                     \
{                                                                                                              \
        return iodefv2_additional_data_new_ ## name ## _nodup_fast(ad, data, strlen(data));                      \
}                                                                                                              \
                                                                                                               \
int iodefv2_additional_data_set_ ## name ## _nodup_fast(iodefv2_additional_data_t *ad, char *data, size_t len)     \
{                                                                                                              \
        return iodefv2_additional_data_set_ptr_nodup_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_ ## type, data, len + 1);\
}                                                                                                              \
                                                                                                               \
int iodefv2_additional_data_set_ ## name ## _nodup(iodefv2_additional_data_t *ad, char *data)                      \
{                                                                                                              \
        return iodefv2_additional_data_set_ ## name ## _nodup_fast(ad, data, strlen(data));                      \
}


#define IODEFV2_ADDITIONAL_DATA_SIMPLE(d_type, d_name, ad_type, c_type, name)                          \
int iodefv2_additional_data_new_ ## name(iodefv2_additional_data_t **ret, c_type val)       \
{                                                                                                                   \
        int retval;                                                                                                 \
                                                                                                                    \
        retval = iodefv2_additional_data_new(ret);                                                               \
        if ( retval < 0 )                                                                                             \
                return retval;                                                               \
                                                                                       \
        iodefv2_additional_data_set_type(*ret, ad_type);                                       \
        iodefv2_data_set_ ## d_name(iodefv2_additional_data_get_data(*ret), val);               \
                                                                                       \
        return retval;                                                                       \
}                                                                                       \
                                                                                       \
void iodefv2_additional_data_set_ ## name(iodefv2_additional_data_t *ptr, c_type val)       \
{                                                                                       \
        iodefv2_additional_data_set_type(ptr, ad_type);                                       \
        iodefv2_data_set_ ## d_name(iodefv2_additional_data_get_data(ptr), val);               \
}                                                                                       \
                                                                                       \
c_type iodefv2_additional_data_get_ ## name(iodefv2_additional_data_t *ptr)                       \
{                                                                                       \
        return iodefv2_data_get_ ## d_name(iodefv2_additional_data_get_data(ptr));               \
}



/*
 * Backward compatibility stuff, remove once 0.9.0 is released.
 */
int iodefv2_additional_data_new_ptr_ref_fast(iodefv2_additional_data_t **nd,
                                           iodefv2_additional_data_type_t type,
                                           const void *ptr, size_t len);

int iodefv2_additional_data_new_ptr_dup_fast(iodefv2_additional_data_t **nd,
                                           iodefv2_additional_data_type_t type,
                                           const void *ptr, size_t len);

int iodefv2_additional_data_new_ptr_nodup_fast(iodefv2_additional_data_t **nd,
                                             iodefv2_additional_data_type_t type,
                                             void *ptr, size_t len);

int iodefv2_additional_data_set_ptr_ref_fast(iodefv2_additional_data_t *data,
                                           iodefv2_additional_data_type_t type, const void *ptr, size_t len);

int iodefv2_additional_data_set_ptr_dup_fast(iodefv2_additional_data_t *data,
                                           iodefv2_additional_data_type_t type, const void *ptr, size_t len);

int iodefv2_additional_data_set_ptr_nodup_fast(iodefv2_additional_data_t *data,
                                             iodefv2_additional_data_type_t type, void *ptr, size_t len);



static const struct {
        iodefv2_additional_data_type_t ad_type;
        iodefv2_data_type_t d_type;
        size_t len;
} iodefv2_additional_data_type_table[] = {
        { IODEFV2_ADDITIONAL_DATA_TYPE_BOOLEAN, IODEFV2_DATA_TYPE_BYTE, sizeof(libiodefv2_bool_t) },
        { IODEFV2_ADDITIONAL_DATA_TYPE_BYTE, IODEFV2_DATA_TYPE_BYTE, sizeof(uint8_t) },
        { IODEFV2_ADDITIONAL_DATA_TYPE_CHARACTER, IODEFV2_DATA_TYPE_CHAR, sizeof(char) },
        { IODEFV2_ADDITIONAL_DATA_TYPE_DATE_TIME, IODEFV2_DATA_TYPE_TIME, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_INTEGER, IODEFV2_DATA_TYPE_INT, sizeof(uint64_t) },
        { IODEFV2_ADDITIONAL_DATA_TYPE_PORTLIST, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_REAL, IODEFV2_DATA_TYPE_FLOAT, sizeof(float) },
        { IODEFV2_ADDITIONAL_DATA_TYPE_STRING, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_FILE, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_FRAME, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_PACKET, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_IPV4_PACKET, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_IPV6_PACKET, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_PATH, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_URL, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_CSV, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_WINREG, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_XML, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_BYTES, IODEFV2_DATA_TYPE_CHAR_STRING, 0 },
        { IODEFV2_ADDITIONAL_DATA_TYPE_NTPSTAMP, IODEFV2_DATA_TYPE_INT, sizeof(uint64_t) },
        { IODEFV2_ADDITIONAL_DATA_TYPE_EXT_VALUE, IODEFV2_DATA_TYPE_CHAR_STRING, IODEFV2_DATA_TYPE_CHAR_STRING }
};

static int check_type(iodefv2_additional_data_type_t type, const unsigned char *buf, size_t len)
{
        if ( type < 0 || (size_t) type >= sizeof(iodefv2_additional_data_type_table) / sizeof(*iodefv2_additional_data_type_table) )
                return libiodefv2_error_verbose(LIBIODEFV2_ERROR_GENERIC, "Invalid IODEFV2AdditionalData type specified");

        if ( iodefv2_additional_data_type_table[type].len != 0 &&
             len > iodefv2_additional_data_type_table[type].len )
                return libiodefv2_error_verbose(LIBIODEFV2_ERROR_GENERIC, "Provided value length does not match specified type length");

        if ( iodefv2_additional_data_type_table[type].len == 0 && len < 1 )
                return libiodefv2_error_verbose(LIBIODEFV2_ERROR_GENERIC, "Invalid value length for this type");

        if ( type == IODEFV2_ADDITIONAL_DATA_TYPE_PORTLIST || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_STRING || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_FILE || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_FRAME || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_PACKET || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_IPV4_PACKET || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_IPV6_PACKET || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_PATH || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_URL || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_CSV || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_WINREG || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_XML || 
                type == IODEFV2_ADDITIONAL_DATA_TYPE_BYTES || 
                IODEFV2_ADDITIONAL_DATA_TYPE_EXT_VALUE )
                return buf[len - 1] == '\0' ? 0 : libiodefv2_error_verbose(LIBIODEFV2_ERROR_GENERIC, "String is not nul terminated");

        return 0;
}



static iodefv2_data_type_t iodefv2_additional_data_type_to_data_type(iodefv2_additional_data_type_t type)
{
        if ( type < 0 || (size_t) type >= sizeof(iodefv2_additional_data_type_table) / sizeof(*iodefv2_additional_data_type_table) )
                return IODEFV2_DATA_TYPE_UNKNOWN;

        return iodefv2_additional_data_type_table[type].d_type;
}



int iodefv2_additional_data_new_ptr_ref_fast(iodefv2_additional_data_t **nd,
                                           iodefv2_additional_data_type_t type,
                                           const void *ptr, size_t len)
{
        int ret;
        iodefv2_data_type_t dtype;

        ret = check_type(type, ptr, len);
        if ( ret < 0 )
                return ret;

        ret = iodefv2_additional_data_new(nd);
        if ( ret < 0 )
                return ret;

        iodefv2_additional_data_set_type(*nd, type);
        dtype = iodefv2_additional_data_type_to_data_type(type);

        ret = iodefv2_data_set_ptr_ref_fast(iodefv2_additional_data_get_data(*nd), dtype, ptr, len);
        if ( ret < 0 ) {
                iodefv2_additional_data_destroy(*nd);
                return ret;
        }

        return 0;
}



int iodefv2_additional_data_new_ptr_dup_fast(iodefv2_additional_data_t **nd,
                                           iodefv2_additional_data_type_t type,
                                           const void *ptr, size_t len)
{
        int ret;
        iodefv2_data_type_t dtype;

        ret = check_type(type, ptr, len);
        if ( ret < 0 )
                return ret;

        ret = iodefv2_additional_data_new(nd);
        if ( ret < 0 )
                return ret;

        iodefv2_additional_data_set_type(*nd, type);
        dtype = iodefv2_additional_data_type_to_data_type(type);

        ret = iodefv2_data_set_ptr_dup_fast(iodefv2_additional_data_get_data(*nd), dtype, ptr, len);
        if ( ret < 0 ) {
                iodefv2_additional_data_destroy(*nd);
                return ret;
        }

        return 0;
}



int iodefv2_additional_data_new_ptr_nodup_fast(iodefv2_additional_data_t **nd,
                                             iodefv2_additional_data_type_t type,
                                             void *ptr, size_t len)
{
        int ret;
        iodefv2_data_type_t dtype;

        ret = check_type(type, ptr, len);
        if ( ret < 0 )
                return ret;

        ret = iodefv2_additional_data_new(nd);
        if ( ret < 0 )
                return ret;

        iodefv2_additional_data_set_type(*nd, type);
        dtype = iodefv2_additional_data_type_to_data_type(type);

        ret = iodefv2_data_set_ptr_nodup_fast(iodefv2_additional_data_get_data(*nd), dtype, ptr, len);
        if ( ret < 0 ) {
                iodefv2_additional_data_destroy(*nd);
                return ret;
        }

        return ret;
}



int iodefv2_additional_data_set_ptr_ref_fast(iodefv2_additional_data_t *data,
                                           iodefv2_additional_data_type_t type, const void *ptr, size_t len)
{
        int ret;

        ret = check_type(type, ptr, len);
        if ( ret < 0 )
                return ret;

        iodefv2_additional_data_set_type(data, type);

        return iodefv2_data_set_ptr_ref_fast(iodefv2_additional_data_get_data(data),
                                           iodefv2_additional_data_type_to_data_type(type), ptr, len);
}



int iodefv2_additional_data_set_ptr_dup_fast(iodefv2_additional_data_t *data,
                                           iodefv2_additional_data_type_t type, const void *ptr, size_t len)
{
        int ret;

        ret = check_type(type, ptr, len);
        if ( ret < 0 )
                return ret;

        iodefv2_additional_data_set_type(data, type);

        return iodefv2_data_set_ptr_dup_fast(iodefv2_additional_data_get_data(data),
                                           iodefv2_additional_data_type_to_data_type(type), ptr, len);
}


int iodefv2_additional_data_set_ptr_nodup_fast(iodefv2_additional_data_t *data,
                                             iodefv2_additional_data_type_t type, void *ptr, size_t len)
{
        int ret;

        ret = check_type(type, ptr, len);
        if ( ret < 0 )
                return ret;

        iodefv2_additional_data_set_type(data, type);

        return iodefv2_data_set_ptr_nodup_fast(iodefv2_additional_data_get_data(data),
                                             iodefv2_additional_data_type_to_data_type(type), ptr, len);
}
/*
 * Declare stuff
 */
IODEFV2_ADDITIONAL_DATA_SIMPLE(IODEFV2_DATA_TYPE_BYTE, byte, IODEFV2_ADDITIONAL_DATA_TYPE_BOOLEAN, libiodefv2_bool_t, boolean)
IODEFV2_ADDITIONAL_DATA_SIMPLE(IODEFV2_DATA_TYPE_BYTE, byte, IODEFV2_ADDITIONAL_DATA_TYPE_BYTE, uint8_t, byte)
IODEFV2_ADDITIONAL_DATA_SIMPLE(IODEFV2_DATA_TYPE_CHAR, char, IODEFV2_ADDITIONAL_DATA_TYPE_CHARACTER, char, character)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(date_time, DATE_TIME)
IODEFV2_ADDITIONAL_DATA_SIMPLE(IODEFV2_DATA_TYPE_INT, int, IODEFV2_ADDITIONAL_DATA_TYPE_INTEGER, uint32_t, integer)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(portlist, PORTLIST)
IODEFV2_ADDITIONAL_DATA_SIMPLE(IODEFV2_DATA_TYPE_FLOAT, float, IODEFV2_ADDITIONAL_DATA_TYPE_REAL, float, real)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(string, STRING)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(file, FILE)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(frame, FRAME)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(packet, PACKET)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(ipv4_packet, IPV4_PACKET)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(ipv6_packet, IPV6_PACKET)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(path, PATH)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(url, URL)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(csv, CSV)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(winreg, WINREG)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(xml, XML)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(bytes, BYTES)
IODEFV2_ADDITIONAL_DATA_SIMPLE(IODEFV2_DATA_TYPE_INT, int, IODEFV2_ADDITIONAL_DATA_TYPE_NTPSTAMP, uint64_t, ntpstamp)
IODEFV2_ADDITIONAL_DATA_ACCESSOR(ext_value, EXT_VALUE)
/*
 * just make a pointer copy of the embedded data
 */
int iodefv2_additional_data_copy_ref(iodefv2_additional_data_t *src, iodefv2_additional_data_t *dst)
{
        int ret;

        ret = libiodefv2_string_copy_ref(iodefv2_additional_data_get_meaning(src), iodefv2_additional_data_get_meaning(dst));
        if ( ret < 0 )
                return ret;

        iodefv2_additional_data_set_type(dst, iodefv2_additional_data_get_type(src));

        return iodefv2_data_copy_ref(iodefv2_additional_data_get_data(src), iodefv2_additional_data_get_data(dst));
}


/*
 * also copy the content of the embedded data
 */
int iodefv2_additional_data_copy_dup(iodefv2_additional_data_t *src, iodefv2_additional_data_t *dst)
{
        int ret;

        ret = libiodefv2_string_copy_dup(iodefv2_additional_data_get_meaning(src), iodefv2_additional_data_get_meaning(dst));
        if ( ret < 0 )
                return ret;

        iodefv2_additional_data_set_type(dst, iodefv2_additional_data_get_type(src));

        return iodefv2_data_copy_dup(iodefv2_additional_data_get_data(src), iodefv2_additional_data_get_data(dst));
}


size_t iodefv2_additional_data_get_len(iodefv2_additional_data_t *data)
{
        return iodefv2_data_get_len(iodefv2_additional_data_get_data(data));
}



libiodefv2_bool_t iodefv2_additional_data_is_empty(iodefv2_additional_data_t *data)
{
        return iodefv2_data_is_empty(iodefv2_additional_data_get_data(data));
}




int iodefv2_additional_data_data_to_string(iodefv2_additional_data_t *ad, libiodefv2_string_t *out)
{
        int ret;
        uint64_t i;
        iodefv2_data_t *data;

        data = iodefv2_additional_data_get_data(ad);
        if ( iodefv2_data_is_empty(data) )
                return 0;

    
    switch ( iodefv2_additional_data_get_type(ad) ) {

        case IODEFV2_ADDITIONAL_DATA_TYPE_NTPSTAMP:
                i = iodefv2_data_get_int(data);
                ret = libiodefv2_string_sprintf(out, "0x%" LIBIODEFV2_PRIx32 ".0x%" LIBIODEFV2_PRIx32, (uint32_t) (i >> 32), (uint32_t) i);
                break;

        default:
                ret = iodefv2_data_to_string(data, out);
                break;
        }
        return ret;

}
/*
 * byte-string specific stuff
 */

int iodefv2_additional_data_new_byte_string_ref(iodefv2_additional_data_t **ad, const unsigned char *data, size_t len)
{
        return iodefv2_additional_data_new_ptr_ref_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_FILE, data, len);
}

int iodefv2_additional_data_set_byte_string_ref(iodefv2_additional_data_t *ad, const unsigned char *data, size_t len)
{
         return iodefv2_additional_data_set_ptr_ref_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_FILE, data, len);
}

int iodefv2_additional_data_new_byte_string_dup(iodefv2_additional_data_t **ad, const unsigned char *data, size_t len)
{
        return iodefv2_additional_data_new_ptr_dup_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_FILE, data, len);
}

int iodefv2_additional_data_set_byte_string_dup(iodefv2_additional_data_t *ad, const unsigned char *data, size_t len)
{
        return iodefv2_additional_data_set_ptr_dup_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_FILE, data, len);
}

int iodefv2_additional_data_new_byte_string_nodup(iodefv2_additional_data_t **ad, unsigned char *data, size_t len)
{
        return iodefv2_additional_data_new_ptr_nodup_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_FILE, data, len);
}

int iodefv2_additional_data_set_byte_string_nodup(iodefv2_additional_data_t *ad, unsigned char *data, size_t len)
{
        return iodefv2_additional_data_set_ptr_nodup_fast(ad, IODEFV2_ADDITIONAL_DATA_TYPE_FILE, data, len);
}
