
/*****
*
* Copyright (C) 2004-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@prelude-ids.com>
*
* This file is part of the Libiodefv2 library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/*
 * This file was automatically generated by our generator, version 1
 *
 * Do not make changes to this file unless you know what you are doing.
 * modify the template interface file instead.
 * IODEFV2 version : RFC5070-bis-26
 * Template file: generate-tree-data.h.mako
 *
 */


typedef struct {
        const char *name;
        libiodefv2_bool_t list;
        libiodefv2_bool_t keyed_list;
        iodefv2_value_type_id_t type;
        iodefv2_class_id_t class;
        int union_id;
} children_list_t;

const children_list_t iodefv2_telephone_children_list[] = {


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_TELEPHONE_TYPE, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "telephone_number", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_certificate_children_list[] = {


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "x509_data", 0, 0, IODEFV2_VALUE_TYPE_DATA, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_key_children_list[] = {


        { "registryaction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_KEY_REGISTRYACTION, 0 },


        { "ext_registryaction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "key_name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "key_value", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_observable_reference_children_list[] = {


        { "uid_ref", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_registry_handle_children_list[] = {


        { "registry", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_REGISTRY_HANDLE_REGISTRY, 0 },


        { "ext_registry", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_time_impact_children_list[] = {


        { "ext_metric", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "duration", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_TIME_IMPACT_DURATION, 0 },


        { "metric", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_TIME_IMPACT_METRIC, 0 },


        { "severity", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_TIME_IMPACT_SEVERITY, 0 },


        { "ext_duration", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_record_pattern_children_list[] = {


        { "instance", 0, 0, IODEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "offset", 0, 0, IODEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "offsetunit", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_RECORD_PATTERN_OFFSETUNIT, 0 },


        { "ext_offsetunit", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_RECORD_PATTERN_TYPE, 0 },

};


const children_list_t iodefv2_reference_children_list[] = {


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "url", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "reference_name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_postal_address_children_list[] = {


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_POSTAL_ADDRESS_TYPE, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "p_address", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_node_role_children_list[] = {


        { "category", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_NODE_ROLE_CATEGORY, 0 },


        { "ext_category", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_incident_id_children_list[] = {


        { "instance", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_INCIDENT_ID_RESTRICTION, 0 },

};


const children_list_t iodefv2_alternative_indicator_id_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_ALTERNATIVE_INDICATOR_ID_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "indicator_reference", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_confidence_children_list[] = {


        { "rating", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_CONFIDENCE_RATING, 0 },


        { "ext_rating", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_system_impact_children_list[] = {


        { "completion", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_SYSTEM_IMPACT_COMPLETION, 0 },


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_SYSTEM_IMPACT_TYPE, 0 },


        { "severity", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_SYSTEM_IMPACT_SEVERITY, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_software_reference_children_list[] = {


        { "dtype", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_SOFTWARE_REFERENCE_DTYPE, 0 },


        { "ext_spec_name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_dtype", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_business_impact_children_list[] = {


        { "ext_severity", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_BUSINESS_IMPACT_TYPE, 0 },


        { "severity", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_BUSINESS_IMPACT_SEVERITY, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_indicator_reference_children_list[] = {


        { "uid_ref", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "version", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "euid_ref", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_email_children_list[] = {


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_EMAIL_TYPE, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "email_to", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_intended_impact_children_list[] = {


        { "ext_severity", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_INTENDED_IMPACT_TYPE, 0 },


        { "severity", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_INTENDED_IMPACT_SEVERITY, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_additional_data_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_ADDITIONAL_DATA_RESTRICTION, 0 },


        { "name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_ADDITIONAL_DATA_TYPE, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "formatid", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "meaning", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_dtype", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "data", 0, 0, IODEFV2_VALUE_TYPE_DATA, 0, 0 },

};


const children_list_t iodefv2_counter_children_list[] = {


        { "meaning", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "unit", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_COUNTER_UNIT, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "duration", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_COUNTER_DURATION, 0 },


        { "ext_unit", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_COUNTER_TYPE, 0 },


        { "ext_duration", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_monetary_impact_children_list[] = {


        { "currency", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "severity", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_MONETARY_IMPACT_SEVERITY, 0 },

};


const children_list_t iodefv2_service_name_children_list[] = {


        { "url", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "iana_service", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_indicator_id_children_list[] = {


        { "version", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_signature_data_children_list[] = {


        { "signature", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_address_children_list[] = {


        { "category", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_ADDRESS_CATEGORY, 0 },


        { "vlan_name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_category", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "vlan_num", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_application_header_children_list[] = {


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },

};


const children_list_t iodefv2_certificate_data_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_CERTIFICATE_DATA_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "certificate", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CERTIFICATE, 0 },

};


const children_list_t iodefv2_threat_actor_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_THREAT_ACTOR_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "url", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "threat_actor_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },

};


const children_list_t iodefv2_method_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_METHOD_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "reference", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_REFERENCE, 0 },

};


const children_list_t iodefv2_alternative_id_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_ALTERNATIVE_ID_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "incident_id", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INCIDENT_ID, 0 },

};


const children_list_t iodefv2_software_children_list[] = {


        { "url", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "software_reference", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SOFTWARE_REFERENCE, 0 },

};


const children_list_t iodefv2_nameservers_children_list[] = {


        { "address", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDRESS, 0 },


        { "server", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_windows_registry_keys_modified_children_list[] = {


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "key", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_KEY, 0 },

};


const children_list_t iodefv2_campaign_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_CAMPAIGN_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "url", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "campaign_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_assessment_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_ASSESSMENT_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "occurrence", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_ASSESSMENT_OCCURRENCE, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "intended_impact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INTENDED_IMPACT, 0 },


        { "confidence", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONFIDENCE, 0 },


        { "time_impact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_TIME_IMPACT, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "monetary_impact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_MONETARY_IMPACT, 0 },


        { "counter", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_COUNTER, 0 },


        { "system_impact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SYSTEM_IMPACT, 0 },


        { "business_impact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_BUSINESS_IMPACT, 0 },


        { "incident_category", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "mitigating_factor", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "cause", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_attack_phase_children_list[] = {


        { "url", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "attack_phase_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_contact_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_CONTACT_RESTRICTION, 0 },


        { "role", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_CONTACT_ROLE, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_role", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_CONTACT_TYPE, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "contact_title", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "telephone", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_TELEPHONE, 0 },


        { "email", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_EMAIL, 0 },


        { "contact_name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "timezone", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "postal_address", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_POSTAL_ADDRESS, 0 },


        { "registry_handle", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_REGISTRY_HANDLE, 0 },

};


const children_list_t iodefv2_related_activity_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_RELATED_ACTIVITY_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "confidence", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONFIDENCE, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "campaign", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CAMPAIGN, 0 },


        { "url", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "threat_actor", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_THREAT_ACTOR, 0 },


        { "indicator_id", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INDICATOR_ID, 0 },


        { "incident_id", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INCIDENT_ID, 0 },

};


const children_list_t iodefv2_domain_contacts_children_list[] = {


        { "contact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONTACT, 0 },


        { "same_domain_contact", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_history_item_children_list[] = {


        { "action", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_HISTORY_ITEM_ACTION, 0 },


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_HISTORY_ITEM_RESTRICTION, 0 },


        { "ext_action", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "contact", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONTACT, 0 },


        { "defined_coa", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "incident_id", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INCIDENT_ID, 0 },


        { "date_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },

};


const children_list_t iodefv2_fuzzy_hash_children_list[] = {


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "software", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SOFTWARE, 0 },

};


const children_list_t iodefv2_hash_children_list[] = {


        { "digest_value", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "digest_method", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "canonicalization_method", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "software", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SOFTWARE, 0 },

};


const children_list_t iodefv2_detection_pattern_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_DETECTION_PATTERN_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "detection_configuration", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "software", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SOFTWARE, 0 },

};


const children_list_t iodefv2_expectation_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_EXPECTATION_RESTRICTION, 0 },


        { "ext_action", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_severity", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "severity", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_EXPECTATION_SEVERITY, 0 },


        { "action", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_EXPECTATION_ACTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "end_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "defined_coa", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "start_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "contact", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONTACT, 0 },

};


const children_list_t iodefv2_domain_data_children_list[] = {


        { "ext_domain_status", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "domain_status", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_DOMAIN_DATA_DOMAIN_STATUS, 0 },


        { "ext_system_status", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "system_status", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_DOMAIN_DATA_SYSTEM_STATUS, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "nameservers", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_NAMESERVERS, 0 },


        { "registration_date", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "domain_contacts", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_DOMAIN_CONTACTS, 0 },


        { "date_domain_was_checked", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "expiration_date", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },

};


const children_list_t iodefv2_hash_data_children_list[] = {


        { "scope", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_HASH_DATA_SCOPE, 0 },


        { "ext_scope", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "hash_target_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "hash", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_HASH, 0 },


        { "fuzzy_hash", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_FUZZY_HASH, 0 },

};


const children_list_t iodefv2_bulk_observable_format_children_list[] = {


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "hash", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_HASH, 0 },

};


const children_list_t iodefv2_history_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_HISTORY_RESTRICTION, 0 },


        { "history_item", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_HISTORY_ITEM, 0 },

};


const children_list_t iodefv2_discovery_children_list[] = {


        { "source", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_DISCOVERY_SOURCE, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_source", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_DISCOVERY_RESTRICTION, 0 },


        { "detection_pattern", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_DETECTION_PATTERN, 0 },


        { "contact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONTACT, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_bulk_observable_children_list[] = {


        { "type", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_BULK_OBSERVABLE_TYPE, 0 },


        { "ext_type", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "bulk_observable_list", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "bulk_observable_format", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_BULK_OBSERVABLE_FORMAT, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },

};


const children_list_t iodefv2_email_data_children_list[] = {


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "email_headers", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "signature_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SIGNATURE_DATA, 0 },


        { "email_subject", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "email_x_mailer", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "hash_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_HASH_DATA, 0 },


        { "email_from", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "application_header", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_APPLICATION_HEADER, 0 },


        { "email_body", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "email_message", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "email_to", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_file_children_list[] = {


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "hash_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_HASH_DATA, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "signature_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SIGNATURE_DATA, 0 },


        { "url", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "software", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SOFTWARE, 0 },


        { "file_name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t iodefv2_node_children_list[] = {


        { "postal_address", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "counter", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_COUNTER, 0 },


        { "location", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "domain_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_DOMAIN_DATA, 0 },


        { "address", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDRESS, 0 },

};


const children_list_t iodefv2_service_children_list[] = {


        { "ip_protocol", 0, 0, IODEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "proto_code", 0, 0, IODEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "portlist", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "proto_field", 0, 0, IODEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "service_name", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SERVICE_NAME, 0 },


        { "application_header", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_APPLICATION_HEADER, 0 },


        { "email_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_EMAIL_DATA, 0 },


        { "proto_type", 0, 0, IODEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "port", 0, 0, IODEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "software", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SOFTWARE, 0 },

};


const children_list_t iodefv2_file_data_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_FILE_DATA_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "file", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_FILE, 0 },

};


const children_list_t iodefv2_system_children_list[] = {


        { "category", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_SYSTEM_CATEGORY, 0 },


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_SYSTEM_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_ownership", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_category", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "spoofed", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_SYSTEM_SPOOFED, 0 },


        { "virtual", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_SYSTEM_VIRTUAL, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ownership", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_SYSTEM_OWNERSHIP, 0 },


        { "interface", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "node", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_NODE, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "service", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SERVICE, 0 },


        { "asset_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "counter", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_COUNTER, 0 },


        { "node_role", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_NODE_ROLE, 0 },


        { "software", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SOFTWARE, 0 },

};


const children_list_t iodefv2_record_data_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_RECORD_DATA_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "url", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "certificate_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CERTIFICATE_DATA, 0 },


        { "record_pattern", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_RECORD_PATTERN, 0 },


        { "date_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "windows_registry_keys_modified", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_WINDOWS_REGISTRY_KEYS_MODIFIED, 0 },


        { "file_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_FILE_DATA, 0 },


        { "software", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SOFTWARE, 0 },

};


const children_list_t iodefv2_record_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_RECORD_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "record_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_RECORD_DATA, 0 },

};


const children_list_t iodefv2_flow_children_list[] = {


        { "system", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SYSTEM, 0 },

};


const children_list_t iodefv2_event_data_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_EVENT_DATA_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "detect_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "report_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "flow", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_FLOW, 0 },


        { "expectation", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_EXPECTATION, 0 },


        { "record", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_RECORD, 0 },


        { "contact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONTACT, 0 },


        { "start_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "end_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "assessment", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ASSESSMENT, 0 },


        { "method", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_METHOD, 0 },


        { "recovery_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "discovery", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_DISCOVERY, 0 },

};


const children_list_t iodefv2_observable_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_OBSERVABLE_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "detection_pattern", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_DETECTION_PATTERN, 0 },


        { "service", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SERVICE, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "system", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_SYSTEM, 0 },


        { "domain_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_DOMAIN_DATA, 0 },


        { "email_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_EMAIL_DATA, 0 },


        { "assessment", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ASSESSMENT, 0 },


        { "record_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_RECORD_DATA, 0 },


        { "reference", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_REFERENCE, 0 },


        { "history_item", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_HISTORY_ITEM, 0 },


        { "bulk_observable", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_BULK_OBSERVABLE, 0 },


        { "certificate_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CERTIFICATE_DATA, 0 },


        { "expectation", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_EXPECTATION, 0 },


        { "windows_registry_keys_modified", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_WINDOWS_REGISTRY_KEYS_MODIFIED, 0 },


        { "address", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDRESS, 0 },


        { "event_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_EVENT_DATA, 0 },


        { "file_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_FILE_DATA, 0 },


        { "registry_handle", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_REGISTRY_HANDLE, 0 },

};


const children_list_t iodefv2_indicator_expression_children_list[] = {


        { "operator", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_INDICATOR_EXPRESSION_OPERATOR, 0 },


        { "ext_operator", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "indicator_reference", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INDICATOR_REFERENCE, 0 },


        { "observable", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_OBSERVABLE, 0 },


        { "confidence", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONFIDENCE, 0 },


        { "indicator_expression", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INDICATOR_EXPRESSION, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },

};


const children_list_t iodefv2_indicator_children_list[] = {


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_INDICATOR_RESTRICTION, 0 },


        { "ext_restriction", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "alternative_indicator_id", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ALTERNATIVE_INDICATOR_ID, 0 },


        { "confidence", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONFIDENCE, 0 },


        { "reference", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_REFERENCE, 0 },


        { "observable", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_OBSERVABLE, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "indicator_expression", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INDICATOR_EXPRESSION, 0 },


        { "contact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONTACT, 0 },


        { "node_role", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_NODE_ROLE, 0 },


        { "start_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "indicator_id", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INDICATOR_ID, 0 },


        { "indicator_reference", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INDICATOR_REFERENCE, 0 },


        { "observable_reference", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_OBSERVABLE_REFERENCE, 0 },


        { "attack_phase", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ATTACK_PHASE, 0 },


        { "end_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },

};


const children_list_t iodefv2_indicator_data_children_list[] = {


        { "indicator", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INDICATOR, 0 },

};


const children_list_t iodefv2_incident_children_list[] = {


        { "status", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_INCIDENT_STATUS, 0 },


        { "lang", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_INCIDENT_LANG, 0 },


        { "ext_purpose", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "purpose", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_INCIDENT_PURPOSE, 0 },


        { "ext_status", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "restriction", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_INCIDENT_RESTRICTION, 0 },


        { "observable_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "history", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_HISTORY, 0 },


        { "start_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "alternative_id", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ALTERNATIVE_ID, 0 },


        { "contact", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_CONTACT, 0 },


        { "related_activity", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_RELATED_ACTIVITY, 0 },


        { "end_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "generation_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "assessment", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ASSESSMENT, 0 },


        { "method", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_METHOD, 0 },


        { "recovery_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "discovery", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_DISCOVERY, 0 },


        { "detect_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "report_time", 0, 0, IODEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "description", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "indicator_data", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INDICATOR_DATA, 0 },


        { "event_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_EVENT_DATA, 0 },


        { "incident_id", 0, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INCIDENT_ID, 0 },

};


const children_list_t iodefv2_document_children_list[] = {


        { "lang", 0, 0, IODEFV2_VALUE_TYPE_ENUM, IODEFV2_CLASS_ID_DOCUMENT_LANG, 0 },


        { "formatid", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "version", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "private_enum_name", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "private_enum_id", 0, 0, IODEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "additional_data", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },


        { "incident", 1, 0, IODEFV2_VALUE_TYPE_CLASS, IODEFV2_CLASS_ID_INCIDENT, 0 },

};


typedef struct {
        const char *name;
        size_t children_list_elem;
        const children_list_t *children_list;
        int (*get_child)(void *ptr, iodefv2_class_child_id_t child, void **ret);
        int (*new_child)(void *ptr, iodefv2_class_child_id_t child, int n, void **ret);
        int (*destroy_child)(void *ptr, iodefv2_class_child_id_t child, int n);
        int (*to_numeric)(const char *name);
        const char *(*to_string)(int val);
        int (*copy)(const void *src, void *dst);
        int (*clone)(const void *src, void **dst);
        int (*compare)(const void *obj1, const void *obj2);
        int (*print)(const void *obj, libiodefv2_io_t *fd);
        int (*print_json)(const void *obj, libiodefv2_io_t *fd);
        int (*print_binary)(const void *obj, libiodefv2_io_t *fd);
        void *(*ref)(void *src);
        void (*destroy)(void *obj);
        libiodefv2_bool_t is_listed;
} object_data_t;

const object_data_t object_data[] =  {
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 0 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 1 */
        { "telephone_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_telephone_type_to_numeric, (void *) iodefv2_telephone_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 2  */
        { "telephone", sizeof(iodefv2_telephone_children_list) / sizeof(*iodefv2_telephone_children_list), iodefv2_telephone_children_list, _iodefv2_telephone_get_child, _iodefv2_telephone_new_child, _iodefv2_telephone_destroy_child, NULL, NULL, (void *) iodefv2_telephone_copy, (void *) iodefv2_telephone_clone, (void *) iodefv2_telephone_compare, (void *) iodefv2_telephone_print, (void *) iodefv2_telephone_print_json, (void *) iodefv2_telephone_write, (void *) iodefv2_telephone_ref, (void *) iodefv2_telephone_destroy, 1 }, /* ID: 3 */
        { "certificate", sizeof(iodefv2_certificate_children_list) / sizeof(*iodefv2_certificate_children_list), iodefv2_certificate_children_list, _iodefv2_certificate_get_child, _iodefv2_certificate_new_child, _iodefv2_certificate_destroy_child, NULL, NULL, (void *) iodefv2_certificate_copy, (void *) iodefv2_certificate_clone, (void *) iodefv2_certificate_compare, (void *) iodefv2_certificate_print, (void *) iodefv2_certificate_print_json, (void *) iodefv2_certificate_write, (void *) iodefv2_certificate_ref, (void *) iodefv2_certificate_destroy, 1 }, /* ID: 4 */
        { "key_registryaction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_key_registryaction_to_numeric, (void *) iodefv2_key_registryaction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 5  */
        { "key", sizeof(iodefv2_key_children_list) / sizeof(*iodefv2_key_children_list), iodefv2_key_children_list, _iodefv2_key_get_child, _iodefv2_key_new_child, _iodefv2_key_destroy_child, NULL, NULL, (void *) iodefv2_key_copy, (void *) iodefv2_key_clone, (void *) iodefv2_key_compare, (void *) iodefv2_key_print, (void *) iodefv2_key_print_json, (void *) iodefv2_key_write, (void *) iodefv2_key_ref, (void *) iodefv2_key_destroy, 1 }, /* ID: 6 */
        { "observable_reference", sizeof(iodefv2_observable_reference_children_list) / sizeof(*iodefv2_observable_reference_children_list), iodefv2_observable_reference_children_list, _iodefv2_observable_reference_get_child, _iodefv2_observable_reference_new_child, _iodefv2_observable_reference_destroy_child, NULL, NULL, (void *) iodefv2_observable_reference_copy, (void *) iodefv2_observable_reference_clone, (void *) iodefv2_observable_reference_compare, (void *) iodefv2_observable_reference_print, (void *) iodefv2_observable_reference_print_json, (void *) iodefv2_observable_reference_write, (void *) iodefv2_observable_reference_ref, (void *) iodefv2_observable_reference_destroy, 0 }, /* ID: 7 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 8 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 9 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 10 */
        { "registry_handle_registry", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_registry_handle_registry_to_numeric, (void *) iodefv2_registry_handle_registry_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 11  */
        { "registry_handle", sizeof(iodefv2_registry_handle_children_list) / sizeof(*iodefv2_registry_handle_children_list), iodefv2_registry_handle_children_list, _iodefv2_registry_handle_get_child, _iodefv2_registry_handle_new_child, _iodefv2_registry_handle_destroy_child, NULL, NULL, (void *) iodefv2_registry_handle_copy, (void *) iodefv2_registry_handle_clone, (void *) iodefv2_registry_handle_compare, (void *) iodefv2_registry_handle_print, (void *) iodefv2_registry_handle_print_json, (void *) iodefv2_registry_handle_write, (void *) iodefv2_registry_handle_ref, (void *) iodefv2_registry_handle_destroy, 1 }, /* ID: 12 */
        { "time_impact_duration", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_time_impact_duration_to_numeric, (void *) iodefv2_time_impact_duration_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 13  */
        { "time_impact_metric", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_time_impact_metric_to_numeric, (void *) iodefv2_time_impact_metric_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 14  */
        { "time_impact_severity", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_time_impact_severity_to_numeric, (void *) iodefv2_time_impact_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 15  */
        { "time_impact", sizeof(iodefv2_time_impact_children_list) / sizeof(*iodefv2_time_impact_children_list), iodefv2_time_impact_children_list, _iodefv2_time_impact_get_child, _iodefv2_time_impact_new_child, _iodefv2_time_impact_destroy_child, NULL, NULL, (void *) iodefv2_time_impact_copy, (void *) iodefv2_time_impact_clone, (void *) iodefv2_time_impact_compare, (void *) iodefv2_time_impact_print, (void *) iodefv2_time_impact_print_json, (void *) iodefv2_time_impact_write, (void *) iodefv2_time_impact_ref, (void *) iodefv2_time_impact_destroy, 1 }, /* ID: 16 */
        { "record_pattern_offsetunit", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_record_pattern_offsetunit_to_numeric, (void *) iodefv2_record_pattern_offsetunit_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 17  */
        { "record_pattern_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_record_pattern_type_to_numeric, (void *) iodefv2_record_pattern_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 18  */
        { "record_pattern", sizeof(iodefv2_record_pattern_children_list) / sizeof(*iodefv2_record_pattern_children_list), iodefv2_record_pattern_children_list, _iodefv2_record_pattern_get_child, _iodefv2_record_pattern_new_child, _iodefv2_record_pattern_destroy_child, NULL, NULL, (void *) iodefv2_record_pattern_copy, (void *) iodefv2_record_pattern_clone, (void *) iodefv2_record_pattern_compare, (void *) iodefv2_record_pattern_print, (void *) iodefv2_record_pattern_print_json, (void *) iodefv2_record_pattern_write, (void *) iodefv2_record_pattern_ref, (void *) iodefv2_record_pattern_destroy, 1 }, /* ID: 19 */
        { "reference", sizeof(iodefv2_reference_children_list) / sizeof(*iodefv2_reference_children_list), iodefv2_reference_children_list, _iodefv2_reference_get_child, _iodefv2_reference_new_child, _iodefv2_reference_destroy_child, NULL, NULL, (void *) iodefv2_reference_copy, (void *) iodefv2_reference_clone, (void *) iodefv2_reference_compare, (void *) iodefv2_reference_print, (void *) iodefv2_reference_print_json, (void *) iodefv2_reference_write, (void *) iodefv2_reference_ref, (void *) iodefv2_reference_destroy, 1 }, /* ID: 20 */
        { "postal_address_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_postal_address_type_to_numeric, (void *) iodefv2_postal_address_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 21  */
        { "postal_address", sizeof(iodefv2_postal_address_children_list) / sizeof(*iodefv2_postal_address_children_list), iodefv2_postal_address_children_list, _iodefv2_postal_address_get_child, _iodefv2_postal_address_new_child, _iodefv2_postal_address_destroy_child, NULL, NULL, (void *) iodefv2_postal_address_copy, (void *) iodefv2_postal_address_clone, (void *) iodefv2_postal_address_compare, (void *) iodefv2_postal_address_print, (void *) iodefv2_postal_address_print_json, (void *) iodefv2_postal_address_write, (void *) iodefv2_postal_address_ref, (void *) iodefv2_postal_address_destroy, 1 }, /* ID: 22 */
        { "node_role_category", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_node_role_category_to_numeric, (void *) iodefv2_node_role_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 23  */
        { "node_role", sizeof(iodefv2_node_role_children_list) / sizeof(*iodefv2_node_role_children_list), iodefv2_node_role_children_list, _iodefv2_node_role_get_child, _iodefv2_node_role_new_child, _iodefv2_node_role_destroy_child, NULL, NULL, (void *) iodefv2_node_role_copy, (void *) iodefv2_node_role_clone, (void *) iodefv2_node_role_compare, (void *) iodefv2_node_role_print, (void *) iodefv2_node_role_print_json, (void *) iodefv2_node_role_write, (void *) iodefv2_node_role_ref, (void *) iodefv2_node_role_destroy, 1 }, /* ID: 24 */
        { "incident_id_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_incident_id_restriction_to_numeric, (void *) iodefv2_incident_id_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 25  */
        { "incident_id", sizeof(iodefv2_incident_id_children_list) / sizeof(*iodefv2_incident_id_children_list), iodefv2_incident_id_children_list, _iodefv2_incident_id_get_child, _iodefv2_incident_id_new_child, _iodefv2_incident_id_destroy_child, NULL, NULL, (void *) iodefv2_incident_id_copy, (void *) iodefv2_incident_id_clone, (void *) iodefv2_incident_id_compare, (void *) iodefv2_incident_id_print, (void *) iodefv2_incident_id_print_json, (void *) iodefv2_incident_id_write, (void *) iodefv2_incident_id_ref, (void *) iodefv2_incident_id_destroy, 1 }, /* ID: 26 */
        { "alternative_indicator_id_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_alternative_indicator_id_restriction_to_numeric, (void *) iodefv2_alternative_indicator_id_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 27  */
        { "alternative_indicator_id", sizeof(iodefv2_alternative_indicator_id_children_list) / sizeof(*iodefv2_alternative_indicator_id_children_list), iodefv2_alternative_indicator_id_children_list, _iodefv2_alternative_indicator_id_get_child, _iodefv2_alternative_indicator_id_new_child, _iodefv2_alternative_indicator_id_destroy_child, NULL, NULL, (void *) iodefv2_alternative_indicator_id_copy, (void *) iodefv2_alternative_indicator_id_clone, (void *) iodefv2_alternative_indicator_id_compare, (void *) iodefv2_alternative_indicator_id_print, (void *) iodefv2_alternative_indicator_id_print_json, (void *) iodefv2_alternative_indicator_id_write, (void *) iodefv2_alternative_indicator_id_ref, (void *) iodefv2_alternative_indicator_id_destroy, 1 }, /* ID: 28 */
        { "confidence_rating", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_confidence_rating_to_numeric, (void *) iodefv2_confidence_rating_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 29  */
        { "confidence", sizeof(iodefv2_confidence_children_list) / sizeof(*iodefv2_confidence_children_list), iodefv2_confidence_children_list, _iodefv2_confidence_get_child, _iodefv2_confidence_new_child, _iodefv2_confidence_destroy_child, NULL, NULL, (void *) iodefv2_confidence_copy, (void *) iodefv2_confidence_clone, (void *) iodefv2_confidence_compare, (void *) iodefv2_confidence_print, (void *) iodefv2_confidence_print_json, (void *) iodefv2_confidence_write, (void *) iodefv2_confidence_ref, (void *) iodefv2_confidence_destroy, 0 }, /* ID: 30 */
        { "system_impact_completion", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_system_impact_completion_to_numeric, (void *) iodefv2_system_impact_completion_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 31  */
        { "system_impact_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_system_impact_type_to_numeric, (void *) iodefv2_system_impact_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 32  */
        { "system_impact_severity", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_system_impact_severity_to_numeric, (void *) iodefv2_system_impact_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 33  */
        { "system_impact", sizeof(iodefv2_system_impact_children_list) / sizeof(*iodefv2_system_impact_children_list), iodefv2_system_impact_children_list, _iodefv2_system_impact_get_child, _iodefv2_system_impact_new_child, _iodefv2_system_impact_destroy_child, NULL, NULL, (void *) iodefv2_system_impact_copy, (void *) iodefv2_system_impact_clone, (void *) iodefv2_system_impact_compare, (void *) iodefv2_system_impact_print, (void *) iodefv2_system_impact_print_json, (void *) iodefv2_system_impact_write, (void *) iodefv2_system_impact_ref, (void *) iodefv2_system_impact_destroy, 1 }, /* ID: 34 */
        { "software_reference_dtype", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_software_reference_dtype_to_numeric, (void *) iodefv2_software_reference_dtype_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 35  */
        { "software_reference", sizeof(iodefv2_software_reference_children_list) / sizeof(*iodefv2_software_reference_children_list), iodefv2_software_reference_children_list, _iodefv2_software_reference_get_child, _iodefv2_software_reference_new_child, _iodefv2_software_reference_destroy_child, NULL, NULL, (void *) iodefv2_software_reference_copy, (void *) iodefv2_software_reference_clone, (void *) iodefv2_software_reference_compare, (void *) iodefv2_software_reference_print, (void *) iodefv2_software_reference_print_json, (void *) iodefv2_software_reference_write, (void *) iodefv2_software_reference_ref, (void *) iodefv2_software_reference_destroy, 0 }, /* ID: 36 */
        { "business_impact_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_business_impact_type_to_numeric, (void *) iodefv2_business_impact_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 37  */
        { "business_impact_severity", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_business_impact_severity_to_numeric, (void *) iodefv2_business_impact_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 38  */
        { "business_impact", sizeof(iodefv2_business_impact_children_list) / sizeof(*iodefv2_business_impact_children_list), iodefv2_business_impact_children_list, _iodefv2_business_impact_get_child, _iodefv2_business_impact_new_child, _iodefv2_business_impact_destroy_child, NULL, NULL, (void *) iodefv2_business_impact_copy, (void *) iodefv2_business_impact_clone, (void *) iodefv2_business_impact_compare, (void *) iodefv2_business_impact_print, (void *) iodefv2_business_impact_print_json, (void *) iodefv2_business_impact_write, (void *) iodefv2_business_impact_ref, (void *) iodefv2_business_impact_destroy, 1 }, /* ID: 39 */
        { "indicator_reference", sizeof(iodefv2_indicator_reference_children_list) / sizeof(*iodefv2_indicator_reference_children_list), iodefv2_indicator_reference_children_list, _iodefv2_indicator_reference_get_child, _iodefv2_indicator_reference_new_child, _iodefv2_indicator_reference_destroy_child, NULL, NULL, (void *) iodefv2_indicator_reference_copy, (void *) iodefv2_indicator_reference_clone, (void *) iodefv2_indicator_reference_compare, (void *) iodefv2_indicator_reference_print, (void *) iodefv2_indicator_reference_print_json, (void *) iodefv2_indicator_reference_write, (void *) iodefv2_indicator_reference_ref, (void *) iodefv2_indicator_reference_destroy, 1 }, /* ID: 40 */
        { "email_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_email_type_to_numeric, (void *) iodefv2_email_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 41  */
        { "email", sizeof(iodefv2_email_children_list) / sizeof(*iodefv2_email_children_list), iodefv2_email_children_list, _iodefv2_email_get_child, _iodefv2_email_new_child, _iodefv2_email_destroy_child, NULL, NULL, (void *) iodefv2_email_copy, (void *) iodefv2_email_clone, (void *) iodefv2_email_compare, (void *) iodefv2_email_print, (void *) iodefv2_email_print_json, (void *) iodefv2_email_write, (void *) iodefv2_email_ref, (void *) iodefv2_email_destroy, 1 }, /* ID: 42 */
        { "intended_impact_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_intended_impact_type_to_numeric, (void *) iodefv2_intended_impact_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 43  */
        { "intended_impact_severity", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_intended_impact_severity_to_numeric, (void *) iodefv2_intended_impact_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 44  */
        { "intended_impact", sizeof(iodefv2_intended_impact_children_list) / sizeof(*iodefv2_intended_impact_children_list), iodefv2_intended_impact_children_list, _iodefv2_intended_impact_get_child, _iodefv2_intended_impact_new_child, _iodefv2_intended_impact_destroy_child, NULL, NULL, (void *) iodefv2_intended_impact_copy, (void *) iodefv2_intended_impact_clone, (void *) iodefv2_intended_impact_compare, (void *) iodefv2_intended_impact_print, (void *) iodefv2_intended_impact_print_json, (void *) iodefv2_intended_impact_write, (void *) iodefv2_intended_impact_ref, (void *) iodefv2_intended_impact_destroy, 1 }, /* ID: 45 */
        { "additional_data_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_additional_data_restriction_to_numeric, (void *) iodefv2_additional_data_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 46  */
        { "additional_data_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_additional_data_type_to_numeric, (void *) iodefv2_additional_data_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 47  */
        { "additional_data", sizeof(iodefv2_additional_data_children_list) / sizeof(*iodefv2_additional_data_children_list), iodefv2_additional_data_children_list, _iodefv2_additional_data_get_child, _iodefv2_additional_data_new_child, _iodefv2_additional_data_destroy_child, NULL, NULL, (void *) iodefv2_additional_data_copy, (void *) iodefv2_additional_data_clone, (void *) iodefv2_additional_data_compare, (void *) iodefv2_additional_data_print, (void *) iodefv2_additional_data_print_json, (void *) iodefv2_additional_data_write, (void *) iodefv2_additional_data_ref, (void *) iodefv2_additional_data_destroy, 1 }, /* ID: 48 */
        { "counter_unit", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_counter_unit_to_numeric, (void *) iodefv2_counter_unit_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 49  */
        { "counter_duration", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_counter_duration_to_numeric, (void *) iodefv2_counter_duration_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 50  */
        { "counter_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_counter_type_to_numeric, (void *) iodefv2_counter_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 51  */
        { "counter", sizeof(iodefv2_counter_children_list) / sizeof(*iodefv2_counter_children_list), iodefv2_counter_children_list, _iodefv2_counter_get_child, _iodefv2_counter_new_child, _iodefv2_counter_destroy_child, NULL, NULL, (void *) iodefv2_counter_copy, (void *) iodefv2_counter_clone, (void *) iodefv2_counter_compare, (void *) iodefv2_counter_print, (void *) iodefv2_counter_print_json, (void *) iodefv2_counter_write, (void *) iodefv2_counter_ref, (void *) iodefv2_counter_destroy, 1 }, /* ID: 52 */
        { "monetary_impact_severity", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_monetary_impact_severity_to_numeric, (void *) iodefv2_monetary_impact_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 53  */
        { "monetary_impact", sizeof(iodefv2_monetary_impact_children_list) / sizeof(*iodefv2_monetary_impact_children_list), iodefv2_monetary_impact_children_list, _iodefv2_monetary_impact_get_child, _iodefv2_monetary_impact_new_child, _iodefv2_monetary_impact_destroy_child, NULL, NULL, (void *) iodefv2_monetary_impact_copy, (void *) iodefv2_monetary_impact_clone, (void *) iodefv2_monetary_impact_compare, (void *) iodefv2_monetary_impact_print, (void *) iodefv2_monetary_impact_print_json, (void *) iodefv2_monetary_impact_write, (void *) iodefv2_monetary_impact_ref, (void *) iodefv2_monetary_impact_destroy, 1 }, /* ID: 54 */
        { "service_name", sizeof(iodefv2_service_name_children_list) / sizeof(*iodefv2_service_name_children_list), iodefv2_service_name_children_list, _iodefv2_service_name_get_child, _iodefv2_service_name_new_child, _iodefv2_service_name_destroy_child, NULL, NULL, (void *) iodefv2_service_name_copy, (void *) iodefv2_service_name_clone, (void *) iodefv2_service_name_compare, (void *) iodefv2_service_name_print, (void *) iodefv2_service_name_print_json, (void *) iodefv2_service_name_write, (void *) iodefv2_service_name_ref, (void *) iodefv2_service_name_destroy, 0 }, /* ID: 55 */
        { "indicator_id", sizeof(iodefv2_indicator_id_children_list) / sizeof(*iodefv2_indicator_id_children_list), iodefv2_indicator_id_children_list, _iodefv2_indicator_id_get_child, _iodefv2_indicator_id_new_child, _iodefv2_indicator_id_destroy_child, NULL, NULL, (void *) iodefv2_indicator_id_copy, (void *) iodefv2_indicator_id_clone, (void *) iodefv2_indicator_id_compare, (void *) iodefv2_indicator_id_print, (void *) iodefv2_indicator_id_print_json, (void *) iodefv2_indicator_id_write, (void *) iodefv2_indicator_id_ref, (void *) iodefv2_indicator_id_destroy, 1 }, /* ID: 56 */
        { "signature_data", sizeof(iodefv2_signature_data_children_list) / sizeof(*iodefv2_signature_data_children_list), iodefv2_signature_data_children_list, _iodefv2_signature_data_get_child, _iodefv2_signature_data_new_child, _iodefv2_signature_data_destroy_child, NULL, NULL, (void *) iodefv2_signature_data_copy, (void *) iodefv2_signature_data_clone, (void *) iodefv2_signature_data_compare, (void *) iodefv2_signature_data_print, (void *) iodefv2_signature_data_print_json, (void *) iodefv2_signature_data_write, (void *) iodefv2_signature_data_ref, (void *) iodefv2_signature_data_destroy, 1 }, /* ID: 57 */
        { "address_category", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_address_category_to_numeric, (void *) iodefv2_address_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 58  */
        { "address", sizeof(iodefv2_address_children_list) / sizeof(*iodefv2_address_children_list), iodefv2_address_children_list, _iodefv2_address_get_child, _iodefv2_address_new_child, _iodefv2_address_destroy_child, NULL, NULL, (void *) iodefv2_address_copy, (void *) iodefv2_address_clone, (void *) iodefv2_address_compare, (void *) iodefv2_address_print, (void *) iodefv2_address_print_json, (void *) iodefv2_address_write, (void *) iodefv2_address_ref, (void *) iodefv2_address_destroy, 1 }, /* ID: 59 */
        { "application_header", sizeof(iodefv2_application_header_children_list) / sizeof(*iodefv2_application_header_children_list), iodefv2_application_header_children_list, _iodefv2_application_header_get_child, _iodefv2_application_header_new_child, _iodefv2_application_header_destroy_child, NULL, NULL, (void *) iodefv2_application_header_copy, (void *) iodefv2_application_header_clone, (void *) iodefv2_application_header_compare, (void *) iodefv2_application_header_print, (void *) iodefv2_application_header_print_json, (void *) iodefv2_application_header_write, (void *) iodefv2_application_header_ref, (void *) iodefv2_application_header_destroy, 0 }, /* ID: 60 */
        { "certificate_data_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_certificate_data_restriction_to_numeric, (void *) iodefv2_certificate_data_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 61  */
        { "certificate_data", sizeof(iodefv2_certificate_data_children_list) / sizeof(*iodefv2_certificate_data_children_list), iodefv2_certificate_data_children_list, _iodefv2_certificate_data_get_child, _iodefv2_certificate_data_new_child, _iodefv2_certificate_data_destroy_child, NULL, NULL, (void *) iodefv2_certificate_data_copy, (void *) iodefv2_certificate_data_clone, (void *) iodefv2_certificate_data_compare, (void *) iodefv2_certificate_data_print, (void *) iodefv2_certificate_data_print_json, (void *) iodefv2_certificate_data_write, (void *) iodefv2_certificate_data_ref, (void *) iodefv2_certificate_data_destroy, 1 }, /* ID: 62 */
        { "threat_actor_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_threat_actor_restriction_to_numeric, (void *) iodefv2_threat_actor_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 63  */
        { "threat_actor", sizeof(iodefv2_threat_actor_children_list) / sizeof(*iodefv2_threat_actor_children_list), iodefv2_threat_actor_children_list, _iodefv2_threat_actor_get_child, _iodefv2_threat_actor_new_child, _iodefv2_threat_actor_destroy_child, NULL, NULL, (void *) iodefv2_threat_actor_copy, (void *) iodefv2_threat_actor_clone, (void *) iodefv2_threat_actor_compare, (void *) iodefv2_threat_actor_print, (void *) iodefv2_threat_actor_print_json, (void *) iodefv2_threat_actor_write, (void *) iodefv2_threat_actor_ref, (void *) iodefv2_threat_actor_destroy, 1 }, /* ID: 64 */
        { "method_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_method_restriction_to_numeric, (void *) iodefv2_method_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 65  */
        { "method", sizeof(iodefv2_method_children_list) / sizeof(*iodefv2_method_children_list), iodefv2_method_children_list, _iodefv2_method_get_child, _iodefv2_method_new_child, _iodefv2_method_destroy_child, NULL, NULL, (void *) iodefv2_method_copy, (void *) iodefv2_method_clone, (void *) iodefv2_method_compare, (void *) iodefv2_method_print, (void *) iodefv2_method_print_json, (void *) iodefv2_method_write, (void *) iodefv2_method_ref, (void *) iodefv2_method_destroy, 1 }, /* ID: 66 */
        { "alternative_id_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_alternative_id_restriction_to_numeric, (void *) iodefv2_alternative_id_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 67  */
        { "alternative_id", sizeof(iodefv2_alternative_id_children_list) / sizeof(*iodefv2_alternative_id_children_list), iodefv2_alternative_id_children_list, _iodefv2_alternative_id_get_child, _iodefv2_alternative_id_new_child, _iodefv2_alternative_id_destroy_child, NULL, NULL, (void *) iodefv2_alternative_id_copy, (void *) iodefv2_alternative_id_clone, (void *) iodefv2_alternative_id_compare, (void *) iodefv2_alternative_id_print, (void *) iodefv2_alternative_id_print_json, (void *) iodefv2_alternative_id_write, (void *) iodefv2_alternative_id_ref, (void *) iodefv2_alternative_id_destroy, 0 }, /* ID: 68 */
        { "software", sizeof(iodefv2_software_children_list) / sizeof(*iodefv2_software_children_list), iodefv2_software_children_list, _iodefv2_software_get_child, _iodefv2_software_new_child, _iodefv2_software_destroy_child, NULL, NULL, (void *) iodefv2_software_copy, (void *) iodefv2_software_clone, (void *) iodefv2_software_compare, (void *) iodefv2_software_print, (void *) iodefv2_software_print_json, (void *) iodefv2_software_write, (void *) iodefv2_software_ref, (void *) iodefv2_software_destroy, 1 }, /* ID: 69 */
        { "nameservers", sizeof(iodefv2_nameservers_children_list) / sizeof(*iodefv2_nameservers_children_list), iodefv2_nameservers_children_list, _iodefv2_nameservers_get_child, _iodefv2_nameservers_new_child, _iodefv2_nameservers_destroy_child, NULL, NULL, (void *) iodefv2_nameservers_copy, (void *) iodefv2_nameservers_clone, (void *) iodefv2_nameservers_compare, (void *) iodefv2_nameservers_print, (void *) iodefv2_nameservers_print_json, (void *) iodefv2_nameservers_write, (void *) iodefv2_nameservers_ref, (void *) iodefv2_nameservers_destroy, 1 }, /* ID: 70 */
        { "windows_registry_keys_modified", sizeof(iodefv2_windows_registry_keys_modified_children_list) / sizeof(*iodefv2_windows_registry_keys_modified_children_list), iodefv2_windows_registry_keys_modified_children_list, _iodefv2_windows_registry_keys_modified_get_child, _iodefv2_windows_registry_keys_modified_new_child, _iodefv2_windows_registry_keys_modified_destroy_child, NULL, NULL, (void *) iodefv2_windows_registry_keys_modified_copy, (void *) iodefv2_windows_registry_keys_modified_clone, (void *) iodefv2_windows_registry_keys_modified_compare, (void *) iodefv2_windows_registry_keys_modified_print, (void *) iodefv2_windows_registry_keys_modified_print_json, (void *) iodefv2_windows_registry_keys_modified_write, (void *) iodefv2_windows_registry_keys_modified_ref, (void *) iodefv2_windows_registry_keys_modified_destroy, 1 }, /* ID: 71 */
        { "campaign_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_campaign_restriction_to_numeric, (void *) iodefv2_campaign_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 72  */
        { "campaign", sizeof(iodefv2_campaign_children_list) / sizeof(*iodefv2_campaign_children_list), iodefv2_campaign_children_list, _iodefv2_campaign_get_child, _iodefv2_campaign_new_child, _iodefv2_campaign_destroy_child, NULL, NULL, (void *) iodefv2_campaign_copy, (void *) iodefv2_campaign_clone, (void *) iodefv2_campaign_compare, (void *) iodefv2_campaign_print, (void *) iodefv2_campaign_print_json, (void *) iodefv2_campaign_write, (void *) iodefv2_campaign_ref, (void *) iodefv2_campaign_destroy, 1 }, /* ID: 73 */
        { "assessment_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_assessment_restriction_to_numeric, (void *) iodefv2_assessment_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 74  */
        { "assessment_occurrence", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_assessment_occurrence_to_numeric, (void *) iodefv2_assessment_occurrence_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 75  */
        { "assessment", sizeof(iodefv2_assessment_children_list) / sizeof(*iodefv2_assessment_children_list), iodefv2_assessment_children_list, _iodefv2_assessment_get_child, _iodefv2_assessment_new_child, _iodefv2_assessment_destroy_child, NULL, NULL, (void *) iodefv2_assessment_copy, (void *) iodefv2_assessment_clone, (void *) iodefv2_assessment_compare, (void *) iodefv2_assessment_print, (void *) iodefv2_assessment_print_json, (void *) iodefv2_assessment_write, (void *) iodefv2_assessment_ref, (void *) iodefv2_assessment_destroy, 1 }, /* ID: 76 */
        { "attack_phase", sizeof(iodefv2_attack_phase_children_list) / sizeof(*iodefv2_attack_phase_children_list), iodefv2_attack_phase_children_list, _iodefv2_attack_phase_get_child, _iodefv2_attack_phase_new_child, _iodefv2_attack_phase_destroy_child, NULL, NULL, (void *) iodefv2_attack_phase_copy, (void *) iodefv2_attack_phase_clone, (void *) iodefv2_attack_phase_compare, (void *) iodefv2_attack_phase_print, (void *) iodefv2_attack_phase_print_json, (void *) iodefv2_attack_phase_write, (void *) iodefv2_attack_phase_ref, (void *) iodefv2_attack_phase_destroy, 1 }, /* ID: 77 */
        { "contact_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_contact_restriction_to_numeric, (void *) iodefv2_contact_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 78  */
        { "contact_role", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_contact_role_to_numeric, (void *) iodefv2_contact_role_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 79  */
        { "contact_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_contact_type_to_numeric, (void *) iodefv2_contact_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 80  */
        { "contact", sizeof(iodefv2_contact_children_list) / sizeof(*iodefv2_contact_children_list), iodefv2_contact_children_list, _iodefv2_contact_get_child, _iodefv2_contact_new_child, _iodefv2_contact_destroy_child, NULL, NULL, (void *) iodefv2_contact_copy, (void *) iodefv2_contact_clone, (void *) iodefv2_contact_compare, (void *) iodefv2_contact_print, (void *) iodefv2_contact_print_json, (void *) iodefv2_contact_write, (void *) iodefv2_contact_ref, (void *) iodefv2_contact_destroy, 1 }, /* ID: 81 */
        { "related_activity_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_related_activity_restriction_to_numeric, (void *) iodefv2_related_activity_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 82  */
        { "related_activity", sizeof(iodefv2_related_activity_children_list) / sizeof(*iodefv2_related_activity_children_list), iodefv2_related_activity_children_list, _iodefv2_related_activity_get_child, _iodefv2_related_activity_new_child, _iodefv2_related_activity_destroy_child, NULL, NULL, (void *) iodefv2_related_activity_copy, (void *) iodefv2_related_activity_clone, (void *) iodefv2_related_activity_compare, (void *) iodefv2_related_activity_print, (void *) iodefv2_related_activity_print_json, (void *) iodefv2_related_activity_write, (void *) iodefv2_related_activity_ref, (void *) iodefv2_related_activity_destroy, 0 }, /* ID: 83 */
        { "domain_contacts", sizeof(iodefv2_domain_contacts_children_list) / sizeof(*iodefv2_domain_contacts_children_list), iodefv2_domain_contacts_children_list, _iodefv2_domain_contacts_get_child, _iodefv2_domain_contacts_new_child, _iodefv2_domain_contacts_destroy_child, NULL, NULL, (void *) iodefv2_domain_contacts_copy, (void *) iodefv2_domain_contacts_clone, (void *) iodefv2_domain_contacts_compare, (void *) iodefv2_domain_contacts_print, (void *) iodefv2_domain_contacts_print_json, (void *) iodefv2_domain_contacts_write, (void *) iodefv2_domain_contacts_ref, (void *) iodefv2_domain_contacts_destroy, 0 }, /* ID: 84 */
        { "history_item_action", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_history_item_action_to_numeric, (void *) iodefv2_history_item_action_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 85  */
        { "history_item_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_history_item_restriction_to_numeric, (void *) iodefv2_history_item_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 86  */
        { "history_item", sizeof(iodefv2_history_item_children_list) / sizeof(*iodefv2_history_item_children_list), iodefv2_history_item_children_list, _iodefv2_history_item_get_child, _iodefv2_history_item_new_child, _iodefv2_history_item_destroy_child, NULL, NULL, (void *) iodefv2_history_item_copy, (void *) iodefv2_history_item_clone, (void *) iodefv2_history_item_compare, (void *) iodefv2_history_item_print, (void *) iodefv2_history_item_print_json, (void *) iodefv2_history_item_write, (void *) iodefv2_history_item_ref, (void *) iodefv2_history_item_destroy, 1 }, /* ID: 87 */
        { "fuzzy_hash", sizeof(iodefv2_fuzzy_hash_children_list) / sizeof(*iodefv2_fuzzy_hash_children_list), iodefv2_fuzzy_hash_children_list, _iodefv2_fuzzy_hash_get_child, _iodefv2_fuzzy_hash_new_child, _iodefv2_fuzzy_hash_destroy_child, NULL, NULL, (void *) iodefv2_fuzzy_hash_copy, (void *) iodefv2_fuzzy_hash_clone, (void *) iodefv2_fuzzy_hash_compare, (void *) iodefv2_fuzzy_hash_print, (void *) iodefv2_fuzzy_hash_print_json, (void *) iodefv2_fuzzy_hash_write, (void *) iodefv2_fuzzy_hash_ref, (void *) iodefv2_fuzzy_hash_destroy, 0 }, /* ID: 88 */
        { "hash", sizeof(iodefv2_hash_children_list) / sizeof(*iodefv2_hash_children_list), iodefv2_hash_children_list, _iodefv2_hash_get_child, _iodefv2_hash_new_child, _iodefv2_hash_destroy_child, NULL, NULL, (void *) iodefv2_hash_copy, (void *) iodefv2_hash_clone, (void *) iodefv2_hash_compare, (void *) iodefv2_hash_print, (void *) iodefv2_hash_print_json, (void *) iodefv2_hash_write, (void *) iodefv2_hash_ref, (void *) iodefv2_hash_destroy, 0 }, /* ID: 89 */
        { "detection_pattern_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_detection_pattern_restriction_to_numeric, (void *) iodefv2_detection_pattern_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 90  */
        { "detection_pattern", sizeof(iodefv2_detection_pattern_children_list) / sizeof(*iodefv2_detection_pattern_children_list), iodefv2_detection_pattern_children_list, _iodefv2_detection_pattern_get_child, _iodefv2_detection_pattern_new_child, _iodefv2_detection_pattern_destroy_child, NULL, NULL, (void *) iodefv2_detection_pattern_copy, (void *) iodefv2_detection_pattern_clone, (void *) iodefv2_detection_pattern_compare, (void *) iodefv2_detection_pattern_print, (void *) iodefv2_detection_pattern_print_json, (void *) iodefv2_detection_pattern_write, (void *) iodefv2_detection_pattern_ref, (void *) iodefv2_detection_pattern_destroy, 1 }, /* ID: 91 */
        { "expectation_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_expectation_restriction_to_numeric, (void *) iodefv2_expectation_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 92  */
        { "expectation_severity", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_expectation_severity_to_numeric, (void *) iodefv2_expectation_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 93  */
        { "expectation_action", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_expectation_action_to_numeric, (void *) iodefv2_expectation_action_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 94  */
        { "expectation", sizeof(iodefv2_expectation_children_list) / sizeof(*iodefv2_expectation_children_list), iodefv2_expectation_children_list, _iodefv2_expectation_get_child, _iodefv2_expectation_new_child, _iodefv2_expectation_destroy_child, NULL, NULL, (void *) iodefv2_expectation_copy, (void *) iodefv2_expectation_clone, (void *) iodefv2_expectation_compare, (void *) iodefv2_expectation_print, (void *) iodefv2_expectation_print_json, (void *) iodefv2_expectation_write, (void *) iodefv2_expectation_ref, (void *) iodefv2_expectation_destroy, 1 }, /* ID: 95 */
        { "domain_data_domain_status", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_domain_data_domain_status_to_numeric, (void *) iodefv2_domain_data_domain_status_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 96  */
        { "domain_data_system_status", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_domain_data_system_status_to_numeric, (void *) iodefv2_domain_data_system_status_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 97  */
        { "domain_data", sizeof(iodefv2_domain_data_children_list) / sizeof(*iodefv2_domain_data_children_list), iodefv2_domain_data_children_list, _iodefv2_domain_data_get_child, _iodefv2_domain_data_new_child, _iodefv2_domain_data_destroy_child, NULL, NULL, (void *) iodefv2_domain_data_copy, (void *) iodefv2_domain_data_clone, (void *) iodefv2_domain_data_compare, (void *) iodefv2_domain_data_print, (void *) iodefv2_domain_data_print_json, (void *) iodefv2_domain_data_write, (void *) iodefv2_domain_data_ref, (void *) iodefv2_domain_data_destroy, 1 }, /* ID: 98 */
        { "hash_data_scope", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_hash_data_scope_to_numeric, (void *) iodefv2_hash_data_scope_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 99  */
        { "hash_data", sizeof(iodefv2_hash_data_children_list) / sizeof(*iodefv2_hash_data_children_list), iodefv2_hash_data_children_list, _iodefv2_hash_data_get_child, _iodefv2_hash_data_new_child, _iodefv2_hash_data_destroy_child, NULL, NULL, (void *) iodefv2_hash_data_copy, (void *) iodefv2_hash_data_clone, (void *) iodefv2_hash_data_compare, (void *) iodefv2_hash_data_print, (void *) iodefv2_hash_data_print_json, (void *) iodefv2_hash_data_write, (void *) iodefv2_hash_data_ref, (void *) iodefv2_hash_data_destroy, 1 }, /* ID: 100 */
        { "bulk_observable_format", sizeof(iodefv2_bulk_observable_format_children_list) / sizeof(*iodefv2_bulk_observable_format_children_list), iodefv2_bulk_observable_format_children_list, _iodefv2_bulk_observable_format_get_child, _iodefv2_bulk_observable_format_new_child, _iodefv2_bulk_observable_format_destroy_child, NULL, NULL, (void *) iodefv2_bulk_observable_format_copy, (void *) iodefv2_bulk_observable_format_clone, (void *) iodefv2_bulk_observable_format_compare, (void *) iodefv2_bulk_observable_format_print, (void *) iodefv2_bulk_observable_format_print_json, (void *) iodefv2_bulk_observable_format_write, (void *) iodefv2_bulk_observable_format_ref, (void *) iodefv2_bulk_observable_format_destroy, 0 }, /* ID: 101 */
        { "history_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_history_restriction_to_numeric, (void *) iodefv2_history_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 102  */
        { "history", sizeof(iodefv2_history_children_list) / sizeof(*iodefv2_history_children_list), iodefv2_history_children_list, _iodefv2_history_get_child, _iodefv2_history_new_child, _iodefv2_history_destroy_child, NULL, NULL, (void *) iodefv2_history_copy, (void *) iodefv2_history_clone, (void *) iodefv2_history_compare, (void *) iodefv2_history_print, (void *) iodefv2_history_print_json, (void *) iodefv2_history_write, (void *) iodefv2_history_ref, (void *) iodefv2_history_destroy, 0 }, /* ID: 103 */
        { "discovery_source", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_discovery_source_to_numeric, (void *) iodefv2_discovery_source_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 104  */
        { "discovery_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_discovery_restriction_to_numeric, (void *) iodefv2_discovery_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 105  */
        { "discovery", sizeof(iodefv2_discovery_children_list) / sizeof(*iodefv2_discovery_children_list), iodefv2_discovery_children_list, _iodefv2_discovery_get_child, _iodefv2_discovery_new_child, _iodefv2_discovery_destroy_child, NULL, NULL, (void *) iodefv2_discovery_copy, (void *) iodefv2_discovery_clone, (void *) iodefv2_discovery_compare, (void *) iodefv2_discovery_print, (void *) iodefv2_discovery_print_json, (void *) iodefv2_discovery_write, (void *) iodefv2_discovery_ref, (void *) iodefv2_discovery_destroy, 1 }, /* ID: 106 */
        { "bulk_observable_type", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_bulk_observable_type_to_numeric, (void *) iodefv2_bulk_observable_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 107  */
        { "bulk_observable", sizeof(iodefv2_bulk_observable_children_list) / sizeof(*iodefv2_bulk_observable_children_list), iodefv2_bulk_observable_children_list, _iodefv2_bulk_observable_get_child, _iodefv2_bulk_observable_new_child, _iodefv2_bulk_observable_destroy_child, NULL, NULL, (void *) iodefv2_bulk_observable_copy, (void *) iodefv2_bulk_observable_clone, (void *) iodefv2_bulk_observable_compare, (void *) iodefv2_bulk_observable_print, (void *) iodefv2_bulk_observable_print_json, (void *) iodefv2_bulk_observable_write, (void *) iodefv2_bulk_observable_ref, (void *) iodefv2_bulk_observable_destroy, 0 }, /* ID: 108 */
        { "email_data", sizeof(iodefv2_email_data_children_list) / sizeof(*iodefv2_email_data_children_list), iodefv2_email_data_children_list, _iodefv2_email_data_get_child, _iodefv2_email_data_new_child, _iodefv2_email_data_destroy_child, NULL, NULL, (void *) iodefv2_email_data_copy, (void *) iodefv2_email_data_clone, (void *) iodefv2_email_data_compare, (void *) iodefv2_email_data_print, (void *) iodefv2_email_data_print_json, (void *) iodefv2_email_data_write, (void *) iodefv2_email_data_ref, (void *) iodefv2_email_data_destroy, 0 }, /* ID: 109 */
        { "file", sizeof(iodefv2_file_children_list) / sizeof(*iodefv2_file_children_list), iodefv2_file_children_list, _iodefv2_file_get_child, _iodefv2_file_new_child, _iodefv2_file_destroy_child, NULL, NULL, (void *) iodefv2_file_copy, (void *) iodefv2_file_clone, (void *) iodefv2_file_compare, (void *) iodefv2_file_print, (void *) iodefv2_file_print_json, (void *) iodefv2_file_write, (void *) iodefv2_file_ref, (void *) iodefv2_file_destroy, 1 }, /* ID: 110 */
        { "node", sizeof(iodefv2_node_children_list) / sizeof(*iodefv2_node_children_list), iodefv2_node_children_list, _iodefv2_node_get_child, _iodefv2_node_new_child, _iodefv2_node_destroy_child, NULL, NULL, (void *) iodefv2_node_copy, (void *) iodefv2_node_clone, (void *) iodefv2_node_compare, (void *) iodefv2_node_print, (void *) iodefv2_node_print_json, (void *) iodefv2_node_write, (void *) iodefv2_node_ref, (void *) iodefv2_node_destroy, 0 }, /* ID: 111 */
        { "service", sizeof(iodefv2_service_children_list) / sizeof(*iodefv2_service_children_list), iodefv2_service_children_list, _iodefv2_service_get_child, _iodefv2_service_new_child, _iodefv2_service_destroy_child, NULL, NULL, (void *) iodefv2_service_copy, (void *) iodefv2_service_clone, (void *) iodefv2_service_compare, (void *) iodefv2_service_print, (void *) iodefv2_service_print_json, (void *) iodefv2_service_write, (void *) iodefv2_service_ref, (void *) iodefv2_service_destroy, 1 }, /* ID: 112 */
        { "file_data_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_file_data_restriction_to_numeric, (void *) iodefv2_file_data_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 113  */
        { "file_data", sizeof(iodefv2_file_data_children_list) / sizeof(*iodefv2_file_data_children_list), iodefv2_file_data_children_list, _iodefv2_file_data_get_child, _iodefv2_file_data_new_child, _iodefv2_file_data_destroy_child, NULL, NULL, (void *) iodefv2_file_data_copy, (void *) iodefv2_file_data_clone, (void *) iodefv2_file_data_compare, (void *) iodefv2_file_data_print, (void *) iodefv2_file_data_print_json, (void *) iodefv2_file_data_write, (void *) iodefv2_file_data_ref, (void *) iodefv2_file_data_destroy, 1 }, /* ID: 114 */
        { "system_category", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_system_category_to_numeric, (void *) iodefv2_system_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 115  */
        { "system_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_system_restriction_to_numeric, (void *) iodefv2_system_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 116  */
        { "system_spoofed", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_system_spoofed_to_numeric, (void *) iodefv2_system_spoofed_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 117  */
        { "system_virtual", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_system_virtual_to_numeric, (void *) iodefv2_system_virtual_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 118  */
        { "system_ownership", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_system_ownership_to_numeric, (void *) iodefv2_system_ownership_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 119  */
        { "system", sizeof(iodefv2_system_children_list) / sizeof(*iodefv2_system_children_list), iodefv2_system_children_list, _iodefv2_system_get_child, _iodefv2_system_new_child, _iodefv2_system_destroy_child, NULL, NULL, (void *) iodefv2_system_copy, (void *) iodefv2_system_clone, (void *) iodefv2_system_compare, (void *) iodefv2_system_print, (void *) iodefv2_system_print_json, (void *) iodefv2_system_write, (void *) iodefv2_system_ref, (void *) iodefv2_system_destroy, 1 }, /* ID: 120 */
        { "record_data_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_record_data_restriction_to_numeric, (void *) iodefv2_record_data_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 121  */
        { "record_data", sizeof(iodefv2_record_data_children_list) / sizeof(*iodefv2_record_data_children_list), iodefv2_record_data_children_list, _iodefv2_record_data_get_child, _iodefv2_record_data_new_child, _iodefv2_record_data_destroy_child, NULL, NULL, (void *) iodefv2_record_data_copy, (void *) iodefv2_record_data_clone, (void *) iodefv2_record_data_compare, (void *) iodefv2_record_data_print, (void *) iodefv2_record_data_print_json, (void *) iodefv2_record_data_write, (void *) iodefv2_record_data_ref, (void *) iodefv2_record_data_destroy, 1 }, /* ID: 122 */
        { "record_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_record_restriction_to_numeric, (void *) iodefv2_record_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 123  */
        { "record", sizeof(iodefv2_record_children_list) / sizeof(*iodefv2_record_children_list), iodefv2_record_children_list, _iodefv2_record_get_child, _iodefv2_record_new_child, _iodefv2_record_destroy_child, NULL, NULL, (void *) iodefv2_record_copy, (void *) iodefv2_record_clone, (void *) iodefv2_record_compare, (void *) iodefv2_record_print, (void *) iodefv2_record_print_json, (void *) iodefv2_record_write, (void *) iodefv2_record_ref, (void *) iodefv2_record_destroy, 0 }, /* ID: 124 */
        { "flow", sizeof(iodefv2_flow_children_list) / sizeof(*iodefv2_flow_children_list), iodefv2_flow_children_list, _iodefv2_flow_get_child, _iodefv2_flow_new_child, _iodefv2_flow_destroy_child, NULL, NULL, (void *) iodefv2_flow_copy, (void *) iodefv2_flow_clone, (void *) iodefv2_flow_compare, (void *) iodefv2_flow_print, (void *) iodefv2_flow_print_json, (void *) iodefv2_flow_write, (void *) iodefv2_flow_ref, (void *) iodefv2_flow_destroy, 1 }, /* ID: 125 */
        { "event_data_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_event_data_restriction_to_numeric, (void *) iodefv2_event_data_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 126  */
        { "event_data", sizeof(iodefv2_event_data_children_list) / sizeof(*iodefv2_event_data_children_list), iodefv2_event_data_children_list, _iodefv2_event_data_get_child, _iodefv2_event_data_new_child, _iodefv2_event_data_destroy_child, NULL, NULL, (void *) iodefv2_event_data_copy, (void *) iodefv2_event_data_clone, (void *) iodefv2_event_data_compare, (void *) iodefv2_event_data_print, (void *) iodefv2_event_data_print_json, (void *) iodefv2_event_data_write, (void *) iodefv2_event_data_ref, (void *) iodefv2_event_data_destroy, 1 }, /* ID: 127 */
        { "observable_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_observable_restriction_to_numeric, (void *) iodefv2_observable_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 128  */
        { "observable", sizeof(iodefv2_observable_children_list) / sizeof(*iodefv2_observable_children_list), iodefv2_observable_children_list, _iodefv2_observable_get_child, _iodefv2_observable_new_child, _iodefv2_observable_destroy_child, NULL, NULL, (void *) iodefv2_observable_copy, (void *) iodefv2_observable_clone, (void *) iodefv2_observable_compare, (void *) iodefv2_observable_print, (void *) iodefv2_observable_print_json, (void *) iodefv2_observable_write, (void *) iodefv2_observable_ref, (void *) iodefv2_observable_destroy, 1 }, /* ID: 129 */
        { "indicator_expression_operator", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_indicator_expression_operator_to_numeric, (void *) iodefv2_indicator_expression_operator_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 130  */
        { "indicator_expression", sizeof(iodefv2_indicator_expression_children_list) / sizeof(*iodefv2_indicator_expression_children_list), iodefv2_indicator_expression_children_list, _iodefv2_indicator_expression_get_child, _iodefv2_indicator_expression_new_child, _iodefv2_indicator_expression_destroy_child, NULL, NULL, (void *) iodefv2_indicator_expression_copy, (void *) iodefv2_indicator_expression_clone, (void *) iodefv2_indicator_expression_compare, (void *) iodefv2_indicator_expression_print, (void *) iodefv2_indicator_expression_print_json, (void *) iodefv2_indicator_expression_write, (void *) iodefv2_indicator_expression_ref, (void *) iodefv2_indicator_expression_destroy, 1 }, /* ID: 131 */
        { "indicator_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_indicator_restriction_to_numeric, (void *) iodefv2_indicator_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 132  */
        { "indicator", sizeof(iodefv2_indicator_children_list) / sizeof(*iodefv2_indicator_children_list), iodefv2_indicator_children_list, _iodefv2_indicator_get_child, _iodefv2_indicator_new_child, _iodefv2_indicator_destroy_child, NULL, NULL, (void *) iodefv2_indicator_copy, (void *) iodefv2_indicator_clone, (void *) iodefv2_indicator_compare, (void *) iodefv2_indicator_print, (void *) iodefv2_indicator_print_json, (void *) iodefv2_indicator_write, (void *) iodefv2_indicator_ref, (void *) iodefv2_indicator_destroy, 1 }, /* ID: 133 */
        { "indicator_data", sizeof(iodefv2_indicator_data_children_list) / sizeof(*iodefv2_indicator_data_children_list), iodefv2_indicator_data_children_list, _iodefv2_indicator_data_get_child, _iodefv2_indicator_data_new_child, _iodefv2_indicator_data_destroy_child, NULL, NULL, (void *) iodefv2_indicator_data_copy, (void *) iodefv2_indicator_data_clone, (void *) iodefv2_indicator_data_compare, (void *) iodefv2_indicator_data_print, (void *) iodefv2_indicator_data_print_json, (void *) iodefv2_indicator_data_write, (void *) iodefv2_indicator_data_ref, (void *) iodefv2_indicator_data_destroy, 0 }, /* ID: 134 */
        { "incident_status", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_incident_status_to_numeric, (void *) iodefv2_incident_status_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 135  */
        { "incident_lang", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_incident_lang_to_numeric, (void *) iodefv2_incident_lang_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 136  */
        { "incident_purpose", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_incident_purpose_to_numeric, (void *) iodefv2_incident_purpose_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 137  */
        { "incident_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_incident_restriction_to_numeric, (void *) iodefv2_incident_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 138  */
        { "incident", sizeof(iodefv2_incident_children_list) / sizeof(*iodefv2_incident_children_list), iodefv2_incident_children_list, _iodefv2_incident_get_child, _iodefv2_incident_new_child, _iodefv2_incident_destroy_child, NULL, NULL, (void *) iodefv2_incident_copy, (void *) iodefv2_incident_clone, (void *) iodefv2_incident_compare, (void *) iodefv2_incident_print, (void *) iodefv2_incident_print_json, (void *) iodefv2_incident_write, (void *) iodefv2_incident_ref, (void *) iodefv2_incident_destroy, 1 }, /* ID: 139 */
        { "document_lang", 0, NULL, NULL, NULL, NULL, (void *) iodefv2_document_lang_to_numeric, (void *) iodefv2_document_lang_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 140  */
        { "document", sizeof(iodefv2_document_children_list) / sizeof(*iodefv2_document_children_list), iodefv2_document_children_list, _iodefv2_document_get_child, _iodefv2_document_new_child, _iodefv2_document_destroy_child, NULL, NULL, (void *) iodefv2_document_copy, (void *) iodefv2_document_clone, (void *) iodefv2_document_compare, (void *) iodefv2_document_print, (void *) iodefv2_document_print_json, (void *) iodefv2_document_write, (void *) iodefv2_document_ref, (void *) iodefv2_document_destroy, 0 }, /* ID: 141 */
        { NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }
};
