
/*****
*
* Copyright (C) 2003-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@libidmefv2-ids.com>
*
* This file is part of the LibIdemfv2 library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/* Auto-generated by the iodefv2-document-print.h.mako package */

#ifndef _LIBIODEFV2_IODEFV2_DOCUMENT_PRINT_H
#define _LIBIODEFV2_IODEFV2_DOCUMENT_PRINT_H

#ifdef __cplusplus
 extern "C" {
#endif


void iodefv2_telephone_print(iodefv2_telephone_t *ptr, libiodefv2_io_t *fd);
void iodefv2_certificate_print(iodefv2_certificate_t *ptr, libiodefv2_io_t *fd);
void iodefv2_key_print(iodefv2_key_t *ptr, libiodefv2_io_t *fd);
void iodefv2_observable_reference_print(iodefv2_observable_reference_t *ptr, libiodefv2_io_t *fd);
void iodefv2_domain_contacts_print(iodefv2_domain_contacts_t *ptr, libiodefv2_io_t *fd);
void iodefv2_extension_print(iodefv2_extension_t *ptr, libiodefv2_io_t *fd);
void iodefv2_registry_handle_print(iodefv2_registry_handle_t *ptr, libiodefv2_io_t *fd);
void iodefv2_time_impact_print(iodefv2_time_impact_t *ptr, libiodefv2_io_t *fd);
void iodefv2_record_pattern_print(iodefv2_record_pattern_t *ptr, libiodefv2_io_t *fd);
void iodefv2_reference_print(iodefv2_reference_t *ptr, libiodefv2_io_t *fd);
void iodefv2_postal_address_print(iodefv2_postal_address_t *ptr, libiodefv2_io_t *fd);
void iodefv2_node_role_print(iodefv2_node_role_t *ptr, libiodefv2_io_t *fd);
void iodefv2_nameservers_print(iodefv2_nameservers_t *ptr, libiodefv2_io_t *fd);
void iodefv2_alternative_indicator_id_print(iodefv2_alternative_indicator_id_t *ptr, libiodefv2_io_t *fd);
void iodefv2_confidence_print(iodefv2_confidence_t *ptr, libiodefv2_io_t *fd);
void iodefv2_system_impact_print(iodefv2_system_impact_t *ptr, libiodefv2_io_t *fd);
void iodefv2_discovery_print(iodefv2_discovery_t *ptr, libiodefv2_io_t *fd);
void iodefv2_monetary_impact_print(iodefv2_monetary_impact_t *ptr, libiodefv2_io_t *fd);
void iodefv2_business_impact_print(iodefv2_business_impact_t *ptr, libiodefv2_io_t *fd);
void iodefv2_indicator_reference_print(iodefv2_indicator_reference_t *ptr, libiodefv2_io_t *fd);
void iodefv2_email_print(iodefv2_email_t *ptr, libiodefv2_io_t *fd);
void iodefv2_incident_id_print(iodefv2_incident_id_t *ptr, libiodefv2_io_t *fd);
void iodefv2_counter_print(iodefv2_counter_t *ptr, libiodefv2_io_t *fd);
void iodefv2_software_reference_print(iodefv2_software_reference_t *ptr, libiodefv2_io_t *fd);
void iodefv2_service_name_print(iodefv2_service_name_t *ptr, libiodefv2_io_t *fd);
void iodefv2_intended_impact_print(iodefv2_intended_impact_t *ptr, libiodefv2_io_t *fd);
void iodefv2_indicator_id_print(iodefv2_indicator_id_t *ptr, libiodefv2_io_t *fd);
void iodefv2_signature_data_print(iodefv2_signature_data_t *ptr, libiodefv2_io_t *fd);
void iodefv2_address_print(iodefv2_address_t *ptr, libiodefv2_io_t *fd);
void iodefv2_expectation_print(iodefv2_expectation_t *ptr, libiodefv2_io_t *fd);
void iodefv2_application_header_print(iodefv2_application_header_t *ptr, libiodefv2_io_t *fd);
void iodefv2_certificate_data_print(iodefv2_certificate_data_t *ptr, libiodefv2_io_t *fd);
void iodefv2_history_item_print(iodefv2_history_item_t *ptr, libiodefv2_io_t *fd);
void iodefv2_method_print(iodefv2_method_t *ptr, libiodefv2_io_t *fd);
void iodefv2_alternative_id_print(iodefv2_alternative_id_t *ptr, libiodefv2_io_t *fd);
void iodefv2_software_print(iodefv2_software_t *ptr, libiodefv2_io_t *fd);
void iodefv2_windows_registry_keys_modified_print(iodefv2_windows_registry_keys_modified_t *ptr, libiodefv2_io_t *fd);
void iodefv2_campaign_print(iodefv2_campaign_t *ptr, libiodefv2_io_t *fd);
void iodefv2_domain_data_print(iodefv2_domain_data_t *ptr, libiodefv2_io_t *fd);
void iodefv2_attack_phase_print(iodefv2_attack_phase_t *ptr, libiodefv2_io_t *fd);
void iodefv2_contact_print(iodefv2_contact_t *ptr, libiodefv2_io_t *fd);
void iodefv2_assessment_print(iodefv2_assessment_t *ptr, libiodefv2_io_t *fd);
void iodefv2_threat_actor_print(iodefv2_threat_actor_t *ptr, libiodefv2_io_t *fd);
void iodefv2_related_activity_print(iodefv2_related_activity_t *ptr, libiodefv2_io_t *fd);
void iodefv2_node_print(iodefv2_node_t *ptr, libiodefv2_io_t *fd);
void iodefv2_history_print(iodefv2_history_t *ptr, libiodefv2_io_t *fd);
void iodefv2_hash_print(iodefv2_hash_t *ptr, libiodefv2_io_t *fd);
void iodefv2_detection_pattern_print(iodefv2_detection_pattern_t *ptr, libiodefv2_io_t *fd);
void iodefv2_fuzzy_hash_print(iodefv2_fuzzy_hash_t *ptr, libiodefv2_io_t *fd);
void iodefv2_hash_data_print(iodefv2_hash_data_t *ptr, libiodefv2_io_t *fd);
void iodefv2_bulk_observable_format_print(iodefv2_bulk_observable_format_t *ptr, libiodefv2_io_t *fd);
void iodefv2_bulk_observable_print(iodefv2_bulk_observable_t *ptr, libiodefv2_io_t *fd);
void iodefv2_email_data_print(iodefv2_email_data_t *ptr, libiodefv2_io_t *fd);
void iodefv2_file_print(iodefv2_file_t *ptr, libiodefv2_io_t *fd);
void iodefv2_service_print(iodefv2_service_t *ptr, libiodefv2_io_t *fd);
void iodefv2_file_data_print(iodefv2_file_data_t *ptr, libiodefv2_io_t *fd);
void iodefv2_system_print(iodefv2_system_t *ptr, libiodefv2_io_t *fd);
void iodefv2_record_data_print(iodefv2_record_data_t *ptr, libiodefv2_io_t *fd);
void iodefv2_observable_print(iodefv2_observable_t *ptr, libiodefv2_io_t *fd);
void iodefv2_flow_print(iodefv2_flow_t *ptr, libiodefv2_io_t *fd);
void iodefv2_record_print(iodefv2_record_t *ptr, libiodefv2_io_t *fd);
void iodefv2_indicator_expression_print(iodefv2_indicator_expression_t *ptr, libiodefv2_io_t *fd);
void iodefv2_event_data_print(iodefv2_event_data_t *ptr, libiodefv2_io_t *fd);
void iodefv2_indicator_print(iodefv2_indicator_t *ptr, libiodefv2_io_t *fd);
void iodefv2_indicator_data_print(iodefv2_indicator_data_t *ptr, libiodefv2_io_t *fd);
void iodefv2_incident_print(iodefv2_incident_t *ptr, libiodefv2_io_t *fd);
void iodefv2_document_print(iodefv2_document_t *ptr, libiodefv2_io_t *fd);
 
#ifdef __cplusplus
 }
#endif

#endif /* _LIBIODEFV2_IODEFV2_DOCUMENT_PRINT_H */
